<html lang="en"><head>
<script src="01-Getting_Started_files/libs/quarto-html/popper.min.js"></script>
<script src="01-Getting_Started_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="01-Getting_Started_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-Getting_Started_files/libs/quarto-html/light-border.css" rel="stylesheet"><title>Getting Started with psychinterpreter</title>
  <!-- Needed for testing but not used in final output -->
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
  </style>
  <link href="01-Getting_Started_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

  <script src="01-Getting_Started_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

  <link href="01-Getting_Started_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">

  <script src="01-Getting_Started_files/libs/datatables-binding-0.34.0/datatables.js"></script>

  <script src="01-Getting_Started_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

  <link href="01-Getting_Started_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">

  <link href="01-Getting_Started_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">

  <script src="01-Getting_Started_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>

  <link href="01-Getting_Started_files/libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

  <script src="01-Getting_Started_files/libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>

  <link href="01-Getting_Started_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">

  <script src="01-Getting_Started_files/libs/pagedtable-1.1/js/pagedtable.js"></script>

</head>
<body>

<div class="includes-before">
</div>

<div class="meta">
  <h1>Getting Started with psychinterpreter</h1>

  <p class="subtitle">LLM-Powered Interpretation of Psychometric Analyses</p>

  <p class="author">Matthias Kloft</p>

  <p class="date">2025-11-23</p>


</div>

<main>
<section id="what-is-psychinterpreter" class="level2">
<h2>What is psychinterpreter?</h2>
<p>The <strong>psychinterpreter</strong> package automatically interprets psychometric analysis results using <strong>Large Language Models (LLMs)</strong>. LLMs are AI systems (like ChatGPT, Claude, or open-source alternatives) that can understand and generate human-like text. Instead of manually examining complex statistical output and guessing what patterns represent, you get clear, human-readable interpretations and actionable insights.</p>
<p>The package also provides <strong>variable labeling</strong> functionality to generate short, descriptive labels from variable descriptions, making your data and results more readable.</p>
<p><strong>Currently supported analyses:</strong></p>
<ul>
<li><strong>Factor Analysis</strong> - Interpret factor loadings and suggest meaningful factor names</li>
</ul>
<p><strong>Planned analysis classes:</strong></p>
<ul>
<li>Gaussian Mixture Models - Interpret cluster profiles</li>
<li>Item Response Theory (IRT) - Interpret item diagnostics</li>
<li>Cognitive Diagnostic Models (CDM) - Interpret Q-matrix patterns</li>
</ul>
<p><strong>Use this package when you:</strong></p>
<ul>
<li>Have run a psychometric analysis (e.g., factor analysis, clustering)</li>
<li>Want automated, data-driven interpretations of your results</li>
<li>Need to quickly understand complex patterns in your data</li>
</ul>
</section>
<section id="what-you-need" class="level2">
<h2>What You Need</h2>
<p>Before starting, make sure you have:</p>
<ol type="1">
<li><strong>Analysis results</strong> - from <code>psych::fa()</code>, <code>lavaan::efa()</code>, or similar functions</li>
<li><strong>Variable descriptions</strong> - brief explanations of what each variable measures</li>
<li><strong>A language model</strong> - we recommend <a href="https://ollama.com/">Ollama</a> (free, runs locally, offers cloud-powered models if you have an Ollama account)</li>
</ol>
</section>
<section id="quick-start-example" class="level2">
<h2>Quick Start Example</h2>
<p>Here’s a complete workflow for <strong>factor analysis</strong> using Big Five personality data in just a few lines:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psychinterpreter)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ollamar)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Describe your variables</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>var_info <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">c</span>(<span class="st">"A1"</span>, <span class="st">"A2"</span>, <span class="st">"A3"</span>, ...),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">description =</span> <span class="fu">c</span>(<span class="st">"Am indifferent to others"</span>, <span class="st">"Inquire about others"</span>, ...)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Generate short labels (optional)</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">label_variables</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_info =</span> var_info,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_provider =</span> <span class="st">"ollama"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_model =</span> <span class="st">"gpt-oss:20b-cloud"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_words =</span> <span class="dv">3</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">case =</span> <span class="st">"title"</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Run factor analysis</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>fa_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">fa</span>(bfi[,<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>], <span class="at">nfactors =</span> <span class="dv">5</span>, <span class="at">rotate =</span> <span class="st">"oblimin"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Get LLM interpretation</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>interpretation <span class="ot">&lt;-</span> <span class="fu">interpret</span>(</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit_results =</span> fa_result,</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_info =</span> var_info,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_provider =</span> <span class="st">"ollama"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_model =</span> <span class="st">"gpt-oss:20b-cloud"</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. View results</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(interpretation)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(interpretation)</span></code></pre></div>
</details>
</div>
</section>
<section id="step-by-step-tutorial-factor-analysis" class="level2">
<h2>Step-by-Step Tutorial: Factor Analysis</h2>
<p>This tutorial demonstrates the package using <strong>factor analysis</strong>, but the same workflow applies to other analysis types when they become available.</p>
<p>Let’s walk through a complete example using the Big Five Inventory (BFI) personality data.</p>
<section id="setup" class="level3">
<h3>Setup</h3>
<p>Load the packages we’ll need:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install pacman if needed for easy package loading</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"psychinterpreter"</span>,  <span class="co"># This package</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"psych"</span>,             <span class="co"># For factor analysis</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DT"</span>,        <span class="co"># For nice tables</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"dplyr"</span>,             <span class="co"># For data manipulation</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"pander"</span>             <span class="co"># package for pretty printing</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
</div>
</section>
<section id="load-and-prepare-data" class="level3">
<h3>Load and Prepare Data</h3>
<p>The BFI dataset contains 25 personality items measuring the Big Five traits.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Big Five Inventory data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"bfi"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"bfi.dictionary"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the 25 personality items (remove demographics)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>bfi_items <span class="ot">&lt;-</span> bfi[, <span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>bfi_dict <span class="ot">&lt;-</span> bfi.dictionary[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>, ]</span></code></pre></div>
</details>
</div>
<p>Here’s what the data looks like:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bfi_items, <span class="dv">5</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>   DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-be29b9559d82ace54653" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-be29b9559d82ace54653">{"x":{"filter":"none","vertical":false,"data":[["61617","61618","61620","61621","61622"],[2,2,5,4,2],[4,4,4,4,3],[3,5,5,6,3],[4,2,4,5,4],[4,5,4,5,5],[2,5,4,4,4],[3,4,5,4,4],[3,4,4,3,5],[4,3,2,5,3],[4,4,5,5,2],[3,1,2,5,2],[3,1,4,3,2],[3,6,4,4,5],[4,4,4,4,4],[4,3,5,4,5],[3,3,4,2,2],[4,3,5,5,3],[2,3,4,2,4],[2,5,2,4,4],[3,5,3,1,3],[3,4,4,3,3],[6,2,2,3,3],[3,4,5,4,4],[4,3,5,3,3],[3,3,2,5,3]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>A1<\/th>\n      <th>A2<\/th>\n      <th>A3<\/th>\n      <th>A4<\/th>\n      <th>A5<\/th>\n      <th>C1<\/th>\n      <th>C2<\/th>\n      <th>C3<\/th>\n      <th>C4<\/th>\n      <th>C5<\/th>\n      <th>E1<\/th>\n      <th>E2<\/th>\n      <th>E3<\/th>\n      <th>E4<\/th>\n      <th>E5<\/th>\n      <th>N1<\/th>\n      <th>N2<\/th>\n      <th>N3<\/th>\n      <th>N4<\/th>\n      <th>N5<\/th>\n      <th>O1<\/th>\n      <th>O2<\/th>\n      <th>O3<\/th>\n      <th>O4<\/th>\n      <th>O5<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"A1","targets":1},{"name":"A2","targets":2},{"name":"A3","targets":3},{"name":"A4","targets":4},{"name":"A5","targets":5},{"name":"C1","targets":6},{"name":"C2","targets":7},{"name":"C3","targets":8},{"name":"C4","targets":9},{"name":"C5","targets":10},{"name":"E1","targets":11},{"name":"E2","targets":12},{"name":"E3","targets":13},{"name":"E4","targets":14},{"name":"E5","targets":15},{"name":"N1","targets":16},{"name":"N2","targets":17},{"name":"N3","targets":18},{"name":"N4","targets":19},{"name":"N5","targets":20},{"name":"O1","targets":21},{"name":"O2","targets":22},{"name":"O3","targets":23},{"name":"O4","targets":24},{"name":"O5","targets":25}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>And here are the item descriptions:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bfi_dict <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Item) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-0e324977f1d90dcedc0b" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-0e324977f1d90dcedc0b">{"x":{"filter":"none","vertical":false,"data":[["A1","A2","A3","A4","A5","C1","C2","C3","C4","C5","E1","E2","E3","E4","E5","N1","N2","N3","N4","N5","O1","O2","O3","O4","O5"],["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time.","Don't talk a lot.","Find it difficult to approach others.","Know how to captivate people.","Make friends easily.","Take charge.","Get angry easily.","Get irritated easily.","Have frequent mood swings.","Often feel blue.","Panic easily.","Am full of ideas.","Avoid difficult reading material.","Carry the conversation to a higher level.","Spend time reflecting on things.","Will not probe deeply into a subject."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Item<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Item","targets":1}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="prepare-variable-descriptions" class="level3">
<h3>Prepare Variable Descriptions</h3>
<p>Create a data frame mapping variable names to their descriptions:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>variable_info <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable =</span> <span class="fu">rownames</span>(bfi_dict),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">description =</span> <span class="fu">as.character</span>(bfi_dict<span class="sc">$</span>Item),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(variable_info, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-7beb7558fd79dba11c4c" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-7beb7558fd79dba11c4c">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10"],["A1","A2","A3","A4","A5","C1","C2","C3","C4","C5"],["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>variable<\/th>\n      <th>description<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"variable","targets":1},{"name":"description","targets":2}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="generate-short-variable-labels-optional" class="level3">
<h3>Generate Short Variable Labels (Optional)</h3>
<p>Before running the analysis, we can use LLMs to generate short, descriptive labels from our variable descriptions. This makes the analysis output and plots more readable:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>provider <span class="ot">&lt;-</span> <span class="st">"anthropic"</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>llm <span class="ot">&lt;-</span> ellmer<span class="sc">::</span><span class="fu">models_anthropic</span>()[<span class="dv">1</span>,<span class="st">"id"</span>]</span></code></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate short labels (1-3 words each)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>bfi_labels <span class="ot">&lt;-</span> <span class="fu">label_variables</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_info =</span> variable_info,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_provider =</span> provider,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_model =</span> llm,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">max_words =</span> <span class="dv">3</span>,        <span class="co"># Keep labels concise</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">"_"</span>,            <span class="co"># Use underscores between words</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">case =</span> <span class="st">"title"</span>        <span class="co"># Title Case format</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
</div>
<p>Now replace the original variable names with these short labels:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new variable names combining original names with labels</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>labels <span class="ot">&lt;-</span> <span class="fu">paste</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  bfi_labels<span class="sc">$</span>labels_formatted<span class="sc">$</span>variable,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  bfi_labels<span class="sc">$</span>labels_formatted<span class="sc">$</span>label,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">"-"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply to data and variable_info</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(bfi_items) <span class="ot">&lt;-</span> labels</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>variable_info<span class="sc">$</span>variable <span class="ot">&lt;-</span> labels</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Show updated variable info</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(variable_info, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-29e142a1d6d5ad0013e8" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-29e142a1d6d5ad0013e8">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10"],["A1-Indifferent_To_Others","A2-Inquire_About_Well-Being","A3-Comfort_Others_Effectively","A4-Love_Children","A5-Put_People_Ease","C1-Exacting_Work_Standards","C2-Pursue_Perfect_Results","C3-Plan_Oriented_Approach","C4-Half-Way_Task_Completion","C5-Waste_Time"],["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>variable<\/th>\n      <th>description<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"variable","targets":1},{"name":"description","targets":2}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div>
<blockquote>
<p><strong>Tip</strong></p>
<p><strong>Label Formatting Options</strong></p>
<p>The <code>label_variables()</code> function offers extensive formatting control:</p>
<ul>
<li><strong>Label types</strong>: <code>label_type = "short"</code> (1-3 words), <code>"phrase"</code> (4-7 words), <code>"acronym"</code> (3-5 chars)</li>
<li><strong>Case transformations</strong>: <code>case = "snake"</code>, <code>"camel"</code>, <code>"title"</code>, <code>"upper"</code>, etc.</li>
<li><strong>Simplification</strong>: <code>remove_articles = TRUE</code>, <code>remove_prepositions = TRUE</code>, <code>abbreviate = TRUE</code></li>
<li><strong>Reformatting</strong>: Use <code>reformat_labels()</code> to change formatting without calling the LLM again</li>
</ul>
<p>See <code>?label_variables</code> for all options.</p>
</blockquote>
</div>
</section>
<section id="run-factor-analysis" class="level3">
<h3>Run Factor Analysis</h3>
<p>Now perform a standard exploratory factor analysis with 5 factors using the labeled data:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fa_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">fa</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  bfi_items,  <span class="co"># Now contains labeled variables</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nfactors =</span> <span class="dv">5</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rotate =</span> <span class="st">"oblimin"</span>,  <span class="co"># Oblique rotation</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fm =</span> <span class="st">"ml"</span>            <span class="co"># Maximum likelihood</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
</div>
<p>View the factor loadings (now with readable labels):</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract and display loadings</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>loadings_matrix <span class="ot">&lt;-</span> <span class="fu">unclass</span>(fa_result<span class="sc">$</span>loadings) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(loadings_matrix, <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-71eb350645f315a597c1" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-71eb350645f315a597c1">{"x":{"filter":"none","vertical":false,"data":[["A1-Indifferent_To_Others","A2-Inquire_About_Well-Being","A3-Comfort_Others_Effectively","A4-Love_Children","A5-Put_People_Ease","C1-Exacting_Work_Standards","C2-Pursue_Perfect_Results","C3-Plan_Oriented_Approach","C4-Half-Way_Task_Completion","C5-Waste_Time","E1-Reserved_Communication_Style","E2-Approach_Others_Difficulty","E3-Captivate_People_Easily","E4-Make_Friends_Easily","E5-Take_Charge_Naturally","N1-Easy_Anger_Response","N2-Easy_Irritation_Response","N3-Frequent_Mood_Swings","N4-Often_Feel_Blue","N5-Panic_Easily_Response","O1-Full_Of_Ideas","O2-Avoid_Difficult_Reading","O3-Elevate_Conversation_Level","O4-Spend_Time_Reflecting","O5-Avoid_Deep_Probing"],[0.2,-0.02,-0.03,-0.06,-0.14,0.06,0.13,0.04,0.12,0.14,-0.09,0.06,0.06,0,0.18,0.85,0.82,0.67,0.41,0.44,-0.01,0.16,0.01,0.08,0.11],[-0.36,0.6,0.67,0.46,0.58,-0,0.11,0.11,0.06,0.01,-0.1,-0.09,0.3,0.36,0.08,-0.09,-0.08,0.1,0.09,0.22,0.02,0.21,0.09,0.14,0.1],[-0.14,0.01,-0.07000000000000001,-0.04,-0.17,0.05,0.13,0.08,0.04,0.16,0.5600000000000001,0.67,-0.34,-0.53,-0.39,-0.09,-0.04,0.14,0.42,0.25,-0.06,-0.03,-0.1,0.36,-0.07000000000000001],[0.04,0.09,0.03,0.2,-0,0.53,0.64,0.5600000000000001,-0.64,-0.57,0.1,-0.03,-0.02,0.01,0.27,0.01,0.02,-0.06,-0.16,-0.02,0.06,-0.1,0,-0.04,-0.05],[-0.04,0.03,0.04,-0.15,0.06,0.16,0.06,-0.06,-0.03,0.1,-0.11,-0.07000000000000001,0.31,-0.05,0.22,-0.05,0.01,0.03,0.08,-0.14,0.53,-0.44,0.63,0.38,-0.52]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>ML2<\/th>\n      <th>ML5<\/th>\n      <th>ML1<\/th>\n      <th>ML3<\/th>\n      <th>ML4<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"ML2","targets":1},{"name":"ML5","targets":2},{"name":"ML1","targets":3},{"name":"ML3","targets":4},{"name":"ML4","targets":5}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="get-llm-interpretation" class="level3">
<h3>Get LLM Interpretation</h3>
<p>Now use <code>interpret()</code> to get automatic factor interpretations:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>interpretation <span class="ot">&lt;-</span> <span class="fu">interpret</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit_results =</span> fa_result,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_info =</span> variable_info,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_provider =</span> provider,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_model =</span> llm</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
FACTOR ANALYSIS INTERPRETATION
────────────────────────────────────────────────────────────────────────────────

Number of factors: 5
Loading cutoff: 0.3
LLM used: anthropic - claude-haiku-4-5-20251001
Tokens:
  Input: 0
  Output: 0
Elapsed time: 10.8

SUGGESTED FACTOR NAMES
────────────────────────────────────────────────────────────────────────────────

• Factor 1 (10%): Emotional Reactivity
• Factor 2 (8.4%): Empathic Concern
• Factor 3 (8.3%): Social Introversion
• Factor 4 (8.2%): Conscientious Organization
• Factor 5 (6.6%): Intellectual Curiosity

Total variance explained: 41.4%

FACTOR CORRELATIONS
────────────────────────────────────────────────────────────────────────────────

ML2: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01
ML5: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23
ML1: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17
ML3: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20
ML4: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

DETAILED FACTOR INTERPRETATIONS
────────────────────────────────────────────────────────────────────────────────

Factor 1 (ML2) - Emotional Reactivity
Number of significant loadings: 5
Variance explained: 9.96%
Factor Correlations: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01

Variables:
  1. N1-Easy_Anger_Response, Get angry easily. (Positive, Very Strong, .852)
  2. N2-Easy_Irritation_Response, Get irritated easily. (Positive, Very Strong, .817)
  3. N3-Frequent_Mood_Swings, Have frequent mood swings. (Positive, Strong, .665)
  4. N5-Panic_Easily_Response, Panic easily. (Positive, Moderate, .439)
  5. N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .413)

LLM Interpretation:
ML2 captures neuroticism through heightened emotional reactivity. Strong loadings on irritability (N2=.817), anger
proneness (N1=.852), mood instability (N3=.665), and panic tendency (N5=.439) define this construct. The factor
represents individuals prone to negative emotional states and distress responses. Moderate loading on feeling blue
(N4=.413) reinforces emotional vulnerability. Notably absent are agreeableness and conscientiousness variables,
demonstrating discriminant validity from interpersonal and achievement dimensions. This factor independently measures
emotional instability as a distinct personality trait affecting overall psychological functioning and wellbeing.

════════════════════════════════════════════════════════════════════════════════

Factor 2 (ML5) - Empathic Concern
Number of significant loadings: 7
Variance explained: 8.41%
Factor Correlations: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23

Variables:
  1. A3-Comfort_Others_Effectively, Know how to comfort others. (Positive, Strong, .668)
  2. A2-Inquire_About_Well-Being, Inquire about others' well-being. (Positive, Strong, .603)
  3. A5-Put_People_Ease, Make people feel at ease. (Positive, Strong, .577)
  4. A4-Love_Children, Love children. (Positive, Moderate, .456)
  5. E4-Make_Friends_Easily, Make friends easily. (Positive, Moderate, .362)
  6. A1-Indifferent_To_Others, Am indifferent to the feelings of others. (Negative, Moderate, -.360)
  7. E3-Captivate_People_Easily, Know how to captivate people. (Positive, Moderate, .303)

LLM Interpretation:
ML5 represents compassion and interpersonal warmth centered on genuine concern for others. Strong positive loadings on
comforting ability (A3=.668), inquiring about wellbeing (A2=.603), and putting people at ease (A5=.577) define core
empathy. The strong negative loading on indifference (A1=-.360) emphasizes genuine investment in others' emotional
states. Moderate loadings on making friends easily (E4=.362) and captivating people (E3=.303) indicate interpersonal
effectiveness. This factor demonstrates convergent validity with agreeableness. Factor correlations show modest positive
association with conscientiousness (ML3=.20) and openness (ML4=.23), suggesting empathy complementarily relates to
organized, intellectually curious individuals.

════════════════════════════════════════════════════════════════════════════════

Factor 3 (ML1) - Social Introversion
Number of significant loadings: 7
Variance explained: 8.28%
Factor Correlations: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17

Variables:
  1. E2-Approach_Others_Difficulty, Find it difficult to approach others. (Positive, Strong, .667)
  2. E1-Reserved_Communication_Style, Don't talk a lot. (Positive, Strong, .565)
  3. E4-Make_Friends_Easily, Make friends easily. (Negative, Strong, -.527)
  4. N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .420)
  5. E5-Take_Charge_Naturally, Take charge. (Negative, Moderate, -.394)
  6. O4-Spend_Time_Reflecting, Spend time reflecting on things. (Positive, Moderate, .357)
  7. E3-Captivate_People_Easily, Know how to captivate people. (Negative, Moderate, -.341)

LLM Interpretation:
ML1 captures social withdrawal and interpersonal hesitancy. Strong positive loadings on reserved communication style
(E1=.565) and difficulty approaching others (E2=.667) define social inhibition. Strong negative loadings on
friend-making ease (E4=-.527), natural leadership (E5=-.394), and people captivation (E3=-.341) confirm the introversion
dimension. Moderate loadings on feeling blue (N4=.420) and introspection (O4=.357) suggest rumination accompanying
social withdrawal. This factor inversely relates to extraversion's approach and assertiveness dimensions. Negative
correlations with empathy (ML5=-.31) and conscientiousness (ML3=-.22) indicate socially withdrawn individuals tend less
toward warmth and organized behavior.

════════════════════════════════════════════════════════════════════════════════

Factor 4 (ML3) - Conscientious Organization
Number of significant loadings: 5
Variance explained: 8.19%
Factor Correlations: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20

Variables:
  1. C4-Half-Way_Task_Completion, Do things in a half-way manner. (Negative, Strong, -.643)
  2. C2-Pursue_Perfect_Results, Continue until everything is perfect. (Positive, Strong, .638)
  3. C5-Waste_Time, Waste my time. (Negative, Strong, -.570)
  4. C3-Plan_Oriented_Approach, Do things according to a plan. (Positive, Strong, .564)
  5. C1-Exacting_Work_Standards, Am exacting in my work. (Positive, Strong, .532)

LLM Interpretation:
ML3 represents disciplined, goal-oriented behavior and organizational commitment. Strong positive loadings on
perfectionism (C2=.638), exacting standards (C1=.532), and planning orientation (C3=.564) establish achievement focus.
Strong negative loadings on half-way completion (C4=-.643) and time wasting (C5=-.570) reflect opposite poles of
conscientiousness. Moderate positive loading on natural leadership (E5=.274) suggests organized individuals assume
responsibility. This factor demonstrates convergent validity with conscientiousness dimension. Modest positive
correlations with empathy (ML5=.20) and openness (ML4=.20) indicate conscientious individuals tend toward interpersonal
warmth and intellectual engagement, suggesting conscientiousness complements rather than contradicts these personality
aspects.

════════════════════════════════════════════════════════════════════════════════

Factor 5 (ML4) - Intellectual Curiosity
Number of significant loadings: 6
Variance explained: 6.57%
Factor Correlations: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

Variables:
  1. O3-Elevate_Conversation_Level, Carry the conversation to a higher level. (Positive, Strong, .633)
  2. O1-Full_Of_Ideas, Am full of ideas. (Positive, Strong, .534)
  3. O5-Avoid_Deep_Probing, Will not probe deeply into a subject. (Negative, Strong, -.522)
  4. O2-Avoid_Difficult_Reading, Avoid difficult reading material. (Negative, Moderate, -.441)
  5. O4-Spend_Time_Reflecting, Spend time reflecting on things. (Positive, Moderate, .379)
  6. E3-Captivate_People_Easily, Know how to captivate people. (Positive, Moderate, .315)

LLM Interpretation:
ML4 represents openness through intellectual engagement and cognitive complexity. Strong positive loadings on elevating
conversation level (O3=.633) and full of ideas (O1=.534) reflect intellectual vibrancy. Strong negative loadings on
avoiding difficult reading (O2=-.441) and avoiding deep probing (O5=-.522) demonstrate cognitive engagement rather than
avoidance. Moderate positive loadings on reflection (O4=.379) and captivating people (E3=.315) suggest thoughtful,
engaging communication. This factor shows clear discriminant validity from other dimensions. Modest positive
correlations with empathy (ML5=.23) and conscientiousness (ML3=.20) suggest intellectually curious individuals tend
toward prosocial warmth and organized ambition, representing complementary rather than competing personality traits.

════════════════════════════════════════════════════════════════════════════════

CROSS-LOADING VARIABLES
────────────────────────────────────────────────────────────────────────────────

Variables loading on multiple factors (&gt;= 0.3):
- E3-Captivate_People_Easily: ML5 (.303), ML1 (-.341), ML4 (.315)
- E4-Make_Friends_Easily: ML5 (.362), ML1 (-.527)
- N4-Often_Feel_Blue: ML2 (.413), ML1 (.420)
- O4-Spend_Time_Reflecting: ML1 (.357), ML4 (.379)</code></pre>
</div>
</div>
<div>
<blockquote>
<p><strong>Note</strong></p>
<p><strong>First time using Ollama?</strong></p>
<ol type="1">
<li>Install Ollama from <a href="https://ollama.com/">ollama.com</a> and the <code>ollamar</code> package: <code>install.packages("ollamar")</code></li>
<li>Pull the model: <code>ollamar::pull("gpt-oss:20b-cloud")</code></li>
<li>Start the Ollama server before running <code>interpret()</code></li>
</ol>
</blockquote>
</div>
</section>
<section id="view-results" class="level3">
<h3>View Results</h3>
<p>Print the interpretation report:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(interpretation)</span></code></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>FACTOR ANALYSIS INTERPRETATION
────────────────────────────────────────────────────────────────────────────────

Number of factors: 5
Loading cutoff: 0.3
LLM used: anthropic - claude-haiku-4-5-20251001
Tokens:
  Input: 0
  Output: 0
Elapsed time: 10.8

SUGGESTED FACTOR NAMES
────────────────────────────────────────────────────────────────────────────────

• Factor 1 (10%): Emotional Reactivity
• Factor 2 (8.4%): Empathic Concern
• Factor 3 (8.3%): Social Introversion
• Factor 4 (8.2%): Conscientious Organization
• Factor 5 (6.6%): Intellectual Curiosity

Total variance explained: 41.4%

FACTOR CORRELATIONS
────────────────────────────────────────────────────────────────────────────────

ML2: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01
ML5: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23
ML1: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17
ML3: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20
ML4: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

DETAILED FACTOR INTERPRETATIONS
────────────────────────────────────────────────────────────────────────────────

Factor 1 (ML2) - Emotional Reactivity
Number of significant loadings: 5
Variance explained: 9.96%
Factor Correlations: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01

Variables:
  1. N1-Easy_Anger_Response, Get angry easily. (Positive, Very Strong, .852)
  2. N2-Easy_Irritation_Response, Get irritated easily. (Positive, Very Strong,
  .817)
  3. N3-Frequent_Mood_Swings, Have frequent mood swings. (Positive, Strong,
  .665)
  4. N5-Panic_Easily_Response, Panic easily. (Positive, Moderate, .439)
  5. N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .413)

LLM Interpretation:
ML2 captures neuroticism through heightened emotional reactivity. Strong
loadings on irritability (N2=.817), anger proneness (N1=.852), mood instability
(N3=.665), and panic tendency (N5=.439) define this construct. The factor
represents individuals prone to negative emotional states and distress
responses. Moderate loading on feeling blue (N4=.413) reinforces emotional
vulnerability. Notably absent are agreeableness and conscientiousness variables,
demonstrating discriminant validity from interpersonal and achievement
dimensions. This factor independently measures emotional instability as a
distinct personality trait affecting overall psychological functioning and
wellbeing.

════════════════════════════════════════════════════════════════════════════════

Factor 2 (ML5) - Empathic Concern
Number of significant loadings: 7
Variance explained: 8.41%
Factor Correlations: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23

Variables:
  1. A3-Comfort_Others_Effectively, Know how to comfort others. (Positive,
  Strong, .668)
  2. A2-Inquire_About_Well-Being, Inquire about others' well-being. (Positive,
  Strong, .603)
  3. A5-Put_People_Ease, Make people feel at ease. (Positive, Strong, .577)
  4. A4-Love_Children, Love children. (Positive, Moderate, .456)
  5. E4-Make_Friends_Easily, Make friends easily. (Positive, Moderate, .362)
  6. A1-Indifferent_To_Others, Am indifferent to the feelings of others.
  (Negative, Moderate, -.360)
  7. E3-Captivate_People_Easily, Know how to captivate people. (Positive,
  Moderate, .303)

LLM Interpretation:
ML5 represents compassion and interpersonal warmth centered on genuine concern
for others. Strong positive loadings on comforting ability (A3=.668), inquiring
about wellbeing (A2=.603), and putting people at ease (A5=.577) define core
empathy. The strong negative loading on indifference (A1=-.360) emphasizes
genuine investment in others' emotional states. Moderate loadings on making
friends easily (E4=.362) and captivating people (E3=.303) indicate interpersonal
effectiveness. This factor demonstrates convergent validity with agreeableness.
Factor correlations show modest positive association with conscientiousness
(ML3=.20) and openness (ML4=.23), suggesting empathy complementarily relates to
organized, intellectually curious individuals.

════════════════════════════════════════════════════════════════════════════════

Factor 3 (ML1) - Social Introversion
Number of significant loadings: 7
Variance explained: 8.28%
Factor Correlations: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17

Variables:
  1. E2-Approach_Others_Difficulty, Find it difficult to approach others.
  (Positive, Strong, .667)
  2. E1-Reserved_Communication_Style, Don't talk a lot. (Positive, Strong, .565)
  3. E4-Make_Friends_Easily, Make friends easily. (Negative, Strong, -.527)
  4. N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .420)
  5. E5-Take_Charge_Naturally, Take charge. (Negative, Moderate, -.394)
  6. O4-Spend_Time_Reflecting, Spend time reflecting on things. (Positive,
  Moderate, .357)
  7. E3-Captivate_People_Easily, Know how to captivate people. (Negative,
  Moderate, -.341)

LLM Interpretation:
ML1 captures social withdrawal and interpersonal hesitancy. Strong positive
loadings on reserved communication style (E1=.565) and difficulty approaching
others (E2=.667) define social inhibition. Strong negative loadings on
friend-making ease (E4=-.527), natural leadership (E5=-.394), and people
captivation (E3=-.341) confirm the introversion dimension. Moderate loadings on
feeling blue (N4=.420) and introspection (O4=.357) suggest rumination
accompanying social withdrawal. This factor inversely relates to extraversion's
approach and assertiveness dimensions. Negative correlations with empathy
(ML5=-.31) and conscientiousness (ML3=-.22) indicate socially withdrawn
individuals tend less toward warmth and organized behavior.

════════════════════════════════════════════════════════════════════════════════

Factor 4 (ML3) - Conscientious Organization
Number of significant loadings: 5
Variance explained: 8.19%
Factor Correlations: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20

Variables:
  1. C4-Half-Way_Task_Completion, Do things in a half-way manner. (Negative,
  Strong, -.643)
  2. C2-Pursue_Perfect_Results, Continue until everything is perfect. (Positive,
  Strong, .638)
  3. C5-Waste_Time, Waste my time. (Negative, Strong, -.570)
  4. C3-Plan_Oriented_Approach, Do things according to a plan. (Positive,
  Strong, .564)
  5. C1-Exacting_Work_Standards, Am exacting in my work. (Positive, Strong,
  .532)

LLM Interpretation:
ML3 represents disciplined, goal-oriented behavior and organizational
commitment. Strong positive loadings on perfectionism (C2=.638), exacting
standards (C1=.532), and planning orientation (C3=.564) establish achievement
focus. Strong negative loadings on half-way completion (C4=-.643) and time
wasting (C5=-.570) reflect opposite poles of conscientiousness. Moderate
positive loading on natural leadership (E5=.274) suggests organized individuals
assume responsibility. This factor demonstrates convergent validity with
conscientiousness dimension. Modest positive correlations with empathy (ML5=.20)
and openness (ML4=.20) indicate conscientious individuals tend toward
interpersonal warmth and intellectual engagement, suggesting conscientiousness
complements rather than contradicts these personality aspects.

════════════════════════════════════════════════════════════════════════════════

Factor 5 (ML4) - Intellectual Curiosity
Number of significant loadings: 6
Variance explained: 6.57%
Factor Correlations: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

Variables:
  1. O3-Elevate_Conversation_Level, Carry the conversation to a higher level.
  (Positive, Strong, .633)
  2. O1-Full_Of_Ideas, Am full of ideas. (Positive, Strong, .534)
  3. O5-Avoid_Deep_Probing, Will not probe deeply into a subject. (Negative,
  Strong, -.522)
  4. O2-Avoid_Difficult_Reading, Avoid difficult reading material. (Negative,
  Moderate, -.441)
  5. O4-Spend_Time_Reflecting, Spend time reflecting on things. (Positive,
  Moderate, .379)
  6. E3-Captivate_People_Easily, Know how to captivate people. (Positive,
  Moderate, .315)

LLM Interpretation:
ML4 represents openness through intellectual engagement and cognitive
complexity. Strong positive loadings on elevating conversation level (O3=.633)
and full of ideas (O1=.534) reflect intellectual vibrancy. Strong negative
loadings on avoiding difficult reading (O2=-.441) and avoiding deep probing
(O5=-.522) demonstrate cognitive engagement rather than avoidance. Moderate
positive loadings on reflection (O4=.379) and captivating people (E3=.315)
suggest thoughtful, engaging communication. This factor shows clear discriminant
validity from other dimensions. Modest positive correlations with empathy
(ML5=.23) and conscientiousness (ML3=.20) suggest intellectually curious
individuals tend toward prosocial warmth and organized ambition, representing
complementary rather than competing personality traits.

════════════════════════════════════════════════════════════════════════════════

CROSS-LOADING VARIABLES
────────────────────────────────────────────────────────────────────────────────

Variables loading on multiple factors (&gt;= 0.3):
- E3-Captivate_People_Easily: ML5 (.303), ML1 (-.341), ML4 (.315)
- E4-Make_Friends_Easily: ML5 (.362), ML1 (-.527)
- N4-Often_Feel_Blue: ML2 (.413), ML1 (.420)
- O4-Spend_Time_Reflecting: ML1 (.357), ML4 (.379)</code></pre>
</div>
</div>
<p>The output shows: - Suggested factor names - Which variables load on each factor - A brief interpretation of what the factor represents</p>
<p>View suggested factor names:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>suggested_names <span class="ot">&lt;-</span> interpretation<span class="sc">$</span>suggested_names <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">Suggested_Factor_Name =</span> suggested_names) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  DT<span class="sc">::</span><span class="fu">datatable</span>(<span class="at">options =</span> <span class="fu">list</span>(<span class="at">scrollX =</span> <span class="cn">TRUE</span>), <span class="at">colnames =</span> <span class="st">"Suggested Factor Name"</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-5d613e82c036e26f902f" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-5d613e82c036e26f902f">{"x":{"filter":"none","vertical":false,"data":[["ML2","ML5","ML1","ML3","ML4"],["Emotional Reactivity","Empathic Concern","Social Introversion","Conscientious Organization","Intellectual Curiosity"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Suggested Factor Name<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"scrollX":true,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Suggested_Factor_Name","targets":1}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="visualize-factor-structure" class="level3">
<h3>Visualize Factor Structure</h3>
<p>Create a visual representation of the factor loadings:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(interpretation, <span class="at">cutoff =</span> <span class="fl">0.3</span>)</span></code></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img src="01-Getting_Started_files/figure-html/plot-loadings-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows which variables load strongly on each factor, making it easy to see the factor structure at a glance.</p>
</section>
<section id="export-results" class="level3">
<h3>Export Results</h3>
<p>Save your interpretation to a file:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Export as markdown</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">export_interpretation</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  interpretation,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">format =</span> <span class="st">"md"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"bfi_interpretation"</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Export as plain text</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">export_interpretation</span>(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  interpretation,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">format =</span> <span class="st">"txt"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"bfi_interpretation"</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
</div>
</section>
</section>
<section id="customizing-your-interpretation" class="level2">
<h2>Customizing Your Interpretation</h2>
<p>You can control several aspects of the interpretation:</p>
<p><strong>Key parameters:</strong></p>
<ul>
<li><code>cutoff</code>: Threshold for displaying results (e.g., minimum loading for FA)</li>
<li><code>hide_low_loadings</code>: Whether to hide loadings below the cutoff from the LLM</li>
<li><code>word_limit</code>: Control how verbose the LLM interpretations are</li>
<li><code>output_format</code>: Choose between plain text or markdown formatting</li>
<li><code>heading_level</code>: Heading level to start the report with.</li>
</ul>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>interpretation <span class="ot">&lt;-</span> <span class="fu">interpret</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit_results =</span> fa_result,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variable_info =</span> variable_info,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_provider =</span> provider,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">llm_model =</span> llm,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cutoff =</span> <span class="fl">0.4</span>,              <span class="co"># Threshold for including results (default: 0.3)</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">hide_low_loadings =</span> <span class="cn">TRUE</span>,  <span class="co"># hide low loadings below cutoff from the LLM</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">word_limit =</span> <span class="dv">30</span>,          <span class="co"># Max words per interpretation (default: 150)</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">output_format =</span> <span class="st">"markdown"</span>,<span class="co"># Output format: "text" or "markdown"</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">heading_level =</span> <span class="dv">3</span>,         <span class="co"># set heading level for markdown output</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</details>
<section id="factor-analysis-interpretation" class="level3">
<h3>FACTOR ANALYSIS INTERPRETATION</h3>
<p><strong>Number of factors:</strong> 5<br>
<strong>Loading cutoff:</strong> 0.4<br>
<strong>LLM used:</strong> anthropic - claude-haiku-4-5-20251001<br>
<strong>Tokens:</strong><br>
Input: 0<br>
Output: 0<br>
<strong>Elapsed time:</strong> 6.65</p>
<section id="suggested-factor-names" class="level4">
<h4>SUGGESTED FACTOR NAMES</h4>
<ul>
<li><strong>Factor 1 (10%):</strong> <em>Emotional Reactivity</em></li>
<li><strong>Factor 2 (8.4%):</strong> <em>Empathic Concern</em></li>
<li><strong>Factor 3 (8.3%):</strong> <em>Social Introversion</em></li>
<li><strong>Factor 4 (8.2%):</strong> <em>Conscientiousness</em></li>
<li><strong>Factor 5 (6.6%):</strong> <em>Intellectual Engagement</em></li>
</ul>
<p><strong>Total variance explained by all factors: 41.4%</strong></p>
</section>
<section id="factor-correlations" class="level4">
<h4>FACTOR CORRELATIONS</h4>
<ul>
<li><strong>ML2:</strong> ML5 = -.03, ML1 = .23, ML3 = -.21,<br>
ML4 = -.01</li>
<li><strong>ML5:</strong> ML2 = -.03, ML1 = -.31, ML3 = .20,<br>
ML4 = .23</li>
<li><strong>ML1:</strong> ML2 = .23, ML5 = -.31, ML3 = -.22,<br>
ML4 = -.17</li>
<li><strong>ML3:</strong> ML2 = -.21, ML5 = .20, ML1 = -.22,<br>
ML4 = .20</li>
<li><strong>ML4:</strong> ML2 = -.01, ML5 = .23, ML1 = -.17,<br>
ML3 = .20</li>
</ul>
</section>
<section id="detailed-factor-interpretations" class="level4">
<h4>DETAILED FACTOR INTERPRETATIONS</h4>
<section id="factor-1-ml2-emotional-reactivity" class="level5">
<h5>Factor 1 (ML2): Emotional Reactivity</h5>
<p><strong>Number of significant loadings:</strong> 5<br>
<strong>Variance explained:</strong> 9.96%<br>
<strong>Factor Correlations:</strong> ML5 = -.03, ML1 = .23, ML3 = -.21,</p>
<p>ML4 = -.01</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>N1-Easy_Anger_Response, Get angry easily. (Positive, Very Strong, .852)</li>
<li>N2-Easy_Irritation_Response, Get irritated easily. (Positive, Very Strong, .817)</li>
<li>N3-Frequent_Mood_Swings, Have frequent mood swings. (Positive, Strong, .665)</li>
<li>N5-Panic_Easily_Response, Panic easily. (Positive, Moderate, .439)</li>
<li>N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .413)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Captures tendency toward negative emotional responses including anger, irritation, and mood instability. Strong loadings on easy anger and irritation reflect core emotional dysregulation. Weak correlations with other factors suggest emotional reactivity operates independently.</p>
</section>
<section id="factor-2-ml5-empathic-concern" class="level5">
<h5>Factor 2 (ML5): Empathic Concern</h5>
<p><strong>Number of significant loadings:</strong> 4<br>
<strong>Variance explained:</strong> 8.41%<br>
<strong>Factor Correlations:</strong> ML2 = -.03, ML1 = -.31, ML3 = .20,</p>
<p>ML4 = .23</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>A3-Comfort_Others_Effectively, Know how to comfort others. (Positive, Strong, .668)</li>
<li>A2-Inquire_About_Well-Being, Inquire about others’ well-being. (Positive, Strong, .603)</li>
<li>A5-Put_People_Ease, Make people feel at ease. (Positive, Strong, .577)</li>
<li>A4-Love_Children, Love children. (Positive, Moderate, .456)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Measures interpersonal warmth and caring behaviors through inquiring about well-being, comforting others, and social ease. Convergent validity shown by cohesive empathy-related variables. Negative correlation with social anxiety (ML1) indicates empathic individuals approach others readily.</p>
</section>
<section id="factor-3-ml1-social-introversion" class="level5">
<h5>Factor 3 (ML1): Social Introversion</h5>
<p><strong>Number of significant loadings:</strong> 4<br>
<strong>Variance explained:</strong> 8.28%<br>
<strong>Factor Correlations:</strong> ML2 = .23, ML5 = -.31, ML3 = -.22,</p>
<p>ML4 = -.17</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>E2-Approach_Others_Difficulty, Find it difficult to approach others. (Positive, Strong, .667)</li>
<li>E1-Reserved_Communication_Style, Don’t talk a lot. (Positive, Strong, .565)</li>
<li>E4-Make_Friends_Easily, Make friends easily. (Negative, Strong, -.527)</li>
<li>N4-Often_Feel_Blue, Often feel blue. (Positive, Moderate, .420)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Reflects social withdrawal tendency including communication reservation and interpersonal approach difficulty. Negative loading on friend-making ease reinforces introversion construct. Negative correlations with empathic concern (ML5) suggest socially anxious individuals struggle with warmth expression.</p>
</section>
<section id="factor-4-ml3-conscientiousness" class="level5">
<h5>Factor 4 (ML3): Conscientiousness</h5>
<p><strong>Number of significant loadings:</strong> 5<br>
<strong>Variance explained:</strong> 8.19%<br>
<strong>Factor Correlations:</strong> ML2 = -.21, ML5 = .20, ML1 = -.22,</p>
<p>ML4 = .20</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>C4-Half-Way_Task_Completion, Do things in a half-way manner. (Negative, Strong, -.643)</li>
<li>C2-Pursue_Perfect_Results, Continue until everything is perfect. (Positive, Strong, .638)</li>
<li>C5-Waste_Time, Waste my time. (Negative, Strong, -.570)</li>
<li>C3-Plan_Oriented_Approach, Do things according to a plan. (Positive, Strong, .564)</li>
<li>C1-Exacting_Work_Standards, Am exacting in my work. (Positive, Strong, .532)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Encompasses work perfectionism, planning orientation, and task completion commitment. Strong positive loadings on precision and planning with strong negative loadings on incompleteness demonstrate construct coherence. Represents organized, dependable work ethic and attention to quality.</p>
</section>
<section id="factor-5-ml4-intellectual-engagement" class="level5">
<h5>Factor 5 (ML4): Intellectual Engagement</h5>
<p><strong>Number of significant loadings:</strong> 4<br>
<strong>Variance explained:</strong> 6.57%<br>
<strong>Factor Correlations:</strong> ML2 = -.01, ML5 = .23, ML1 = -.17,</p>
<p>ML3 = .20</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>O3-Elevate_Conversation_Level, Carry the conversation to a higher level. (Positive, Strong, .633)</li>
<li>O1-Full_Of_Ideas, Am full of ideas. (Positive, Strong, .534)</li>
<li>O5-Avoid_Deep_Probing, Will not probe deeply into a subject. (Negative, Strong, -.522)</li>
<li>O2-Avoid_Difficult_Reading, Avoid difficult reading material. (Negative, Moderate, -.441)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Assesses openness to complex ideas and thoughtful discourse through ideation and conversation elevation. Negative loadings on material avoidance indicate intellectual curiosity. Positive correlations with conscientiousness and empathy suggest intellectually engaged individuals maintain broader engagement patterns.</p>
</section>
</section>
<section id="cross-loading-variables" class="level4">
<h4>CROSS-LOADING VARIABLES</h4>
<p>Variables loading on multiple factors (&gt;= 0.4):</p>
<ul>
<li><strong>N4-Often_Feel_Blue</strong>: ML2 (.413), ML1 (.420)</li>
</ul>
</section>
<section id="variables-not-covered-by-any-factor" class="level4">
<h4>VARIABLES NOT COVERED BY ANY FACTOR</h4>
<p>Variables with no absolute loadings &gt;= 0.4 (highest absolute loading shown):</p>
<ul>
<li><strong>A1-Indifferent_To_Others</strong> (highest: ML5 = .360)</li>
<li><strong>E3-Captivate_People_Easily</strong> (highest: ML1 = .341)</li>
<li><strong>E5-Take_Charge_Naturally</strong> (highest: ML1 = .394)</li>
<li><strong>O4-Spend_Time_Reflecting</strong> (highest: ML4 = .379)</li>
</ul>
</section>
</section>
</section>
<section id="common-questions" class="level2">
<h2>Common Questions</h2>
<p><strong>Q: What if the LLM interpretation seems wrong?</strong></p>
<p>The LLM bases interpretations on your variable descriptions and statistical results. You can:</p>
<ul>
<li>Provide better, more descriptive variable descriptions</li>
<li>Use a bigger LLM. Small models may struggle with the task and structured output requirements.</li>
<li>Adjust the <code>cutoff</code> and <code>hide_low_loadings</code> parameters to change which results are included</li>
<li>Add context with the <code>additional_info</code> parameter</li>
</ul>
<p><strong>Q: Can I use different LLMs?</strong></p>
<p>Yes! The package supports all providers supported by the <a href="https://ellmer.tidyverse.org/"><code>ellmer</code></a> package, for example:</p>
<ul>
<li><strong>Ollama</strong> (local, free): <code>llm_provider = "ollama"</code></li>
<li><strong>OpenAI</strong> (API key required): <code>llm_provider = "openai"</code></li>
<li><strong>Anthropic Claude</strong> (API key required): <code>llm_provider = "anthropic"</code></li>
</ul>
<p><strong>Q: How do I set API keys for OpenAI or Anthropic?</strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add to your .Renviron file:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">OPENAI_API_KEY =</span> <span class="st">"your-key-here"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="at">ANTHROPIC_API_KEY =</span> <span class="st">"your-key-here"</span>)</span></code></pre></div>
</details>
</div>
<p>Also refer to the documentation of the <code>ellmer</code> <a href="https://ellmer.tidyverse.org/">https://ellmer.tidyverse.org/</a> package.</p>
</section>
<section id="session-info" class="level2">
<h2>Session Info</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pander<span class="sc">::</span><span class="fu">pander</span>(<span class="fu">sessionInfo</span>())</span></code></pre></div>
</details>
<div class="cell-output-display">
<p><strong>R version 4.5.2 (2025-10-31 ucrt)</strong></p>
<p><strong>Platform:</strong> x86_64-w64-mingw32/x64</p>
<p><strong>locale:</strong> <em>LC_COLLATE=German_Germany.utf8</em>, <em>LC_CTYPE=German_Germany.utf8</em>, <em>LC_MONETARY=German_Germany.utf8</em>, <em>LC_NUMERIC=C</em> and <em>LC_TIME=German_Germany.utf8</em></p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>pander(v.0.6.6)</em>, <em>dplyr(v.1.1.4)</em>, <em>DT(v.0.34.0)</em>, <em>psych(v.2.5.6)</em>, <em>psychinterpreter(v.0.0.0.9000)</em> and <em>pacman(v.0.5.1)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>GPArotation(v.2025.3-1)</em>, <em>rappdirs(v.0.3.3)</em>, <em>sass(v.0.4.10)</em>, <em>generics(v.0.1.4)</em>, <em>tidyr(v.1.3.1)</em>, <em>lattice(v.0.22-7)</em>, <em>digest(v.0.6.37)</em>, <em>magrittr(v.2.0.3)</em>, <em>evaluate(v.1.0.5)</em>, <em>grid(v.4.5.2)</em>, <em>RColorBrewer(v.1.1-3)</em>, <em>fastmap(v.1.2.0)</em>, <em>jsonlite(v.2.0.0)</em>, <em>purrr(v.1.0.4)</em>, <em>crosstalk(v.1.2.2)</em>, <em>scales(v.1.4.0)</em>, <em>coro(v.1.1.0)</em>, <em>httr2(v.1.2.1)</em>, <em>jquerylib(v.0.1.4)</em>, <em>mnormt(v.2.1.1)</em>, <em>cli(v.3.6.5)</em>, <em>rlang(v.1.1.6)</em>, <em>withr(v.3.0.2)</em>, <em>cachem(v.1.1.0)</em>, <em>yaml(v.2.3.10)</em>, <em>tools(v.4.5.2)</em>, <em>parallel(v.4.5.2)</em>, <em>ggplot2(v.4.0.1)</em>, <em>curl(v.7.0.0)</em>, <em>vctrs(v.0.6.5)</em>, <em>R6(v.2.6.1)</em>, <em>lifecycle(v.1.0.4)</em>, <em>htmlwidgets(v.1.6.4)</em>, <em>pkgconfig(v.2.0.3)</em>, <em>pillar(v.1.11.1)</em>, <em>bslib(v.0.9.0)</em>, <em>gtable(v.0.3.6)</em>, <em>glue(v.1.8.0)</em>, <em>Rcpp(v.1.1.0)</em>, <em>xfun(v.0.53)</em>, <em>tibble(v.3.3.0)</em>, <em>tidyselect(v.1.2.1)</em>, <em>rstudioapi(v.0.17.1)</em>, <em>knitr(v.1.50)</em>, <em>farver(v.2.1.2)</em>, <em>htmltools(v.0.5.8.1)</em>, <em>nlme(v.3.1-168)</em>, <em>labeling(v.0.4.3)</em>, <em>rmarkdown(v.2.30)</em>, <em>ellmer(v.0.4.0)</em>, <em>compiler(v.4.5.2)</em> and <em>S7(v.0.2.0)</em></p>
</div>
</div>
</section>
</main>

<div class="includes-after">
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div>



</body></html>