<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Getting Started with psychinterpreter • psychinterpreter</title>
<!-- mathjax math --><script src="https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js" integrity="sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI=" crossorigin="anonymous"></script><script>
  window.MathJax = {
    chtml: {
      fontURL: "https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/output/chtml/fonts/woff-v2"
    }
  };
</script><script src="../lightswitch.js"></script><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet">
<script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet">
<link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet">
<script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><script src="01-Getting_Started_files/libs/quarto-html/popper.min.js"></script><script src="01-Getting_Started_files/libs/quarto-html/tippy.umd.min.js"></script><link href="01-Getting_Started_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-Getting_Started_files/libs/quarto-html/light-border.css" rel="stylesheet">
<script src="01-Getting_Started_files/libs/core-js-2.5.3/shim.min.js"></script><script src="01-Getting_Started_files/libs/react-18.2.0/react.min.js"></script><script src="01-Getting_Started_files/libs/react-18.2.0/react-dom.min.js"></script><script src="01-Getting_Started_files/libs/reactwidget-2.0.0/react-tools.js"></script><link href="01-Getting_Started_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="01-Getting_Started_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script><link href="01-Getting_Started_files/libs/reactable-0.4.4/reactable.css" rel="stylesheet">
<script src="01-Getting_Started_files/libs/reactable-binding-0.4.4/reactable.js"></script><link href="01-Getting_Started_files/libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="01-Getting_Started_files/libs/pagedtable-1.1/js/pagedtable.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Getting Started with psychinterpreter">
</head>
<body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top " aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">psychinterpreter</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.0.0.9000</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto">
<li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-articles" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Articles</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-articles">
<li><a class="dropdown-item" href="../articles/01-Getting_Started.html">Getting Started with psychinterpreter</a></li>
    <li><a class="dropdown-item" href="../articles/02-Usage_Patterns.html">`interpret()` Usage Patterns</a></li>
    <li><a class="dropdown-item" href="../articles/03-Variable_Labeling.html">Variable Labeling with LLMs</a></li>
    <li><a class="dropdown-item" href="../articles/04-Gaussian_Mixture.html">Cluster Analysis via Gaussian Mixture Models</a></li>
  </ul>
</li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul>
<ul class="navbar-nav">
<li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json">
</form></li>
<li class="nav-item"><a class="nav-link" href="https://github.com/matthiaskloft/psychinterpreter/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-lightswitch" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true" aria-label="Light switch"><span class="fa fa-sun"></span></button>
  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-lightswitch">
<li><button class="dropdown-item" data-bs-theme-value="light"><span class="fa fa-sun"></span> Light</button></li>
    <li><button class="dropdown-item" data-bs-theme-value="dark"><span class="fa fa-moon"></span> Dark</button></li>
    <li><button class="dropdown-item" data-bs-theme-value="auto"><span class="fa fa-adjust"></span> Auto</button></li>
  </ul>
</li>
      </ul>
</div>


  </div>
</nav><div class="container template-quarto">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">

      <h1>Getting Started with psychinterpreter</h1>
      <p class="subtitle">LLM-Powered Interpretation of Psychometric Analyses</p>
      <p class="author">Matthias Kloft</p>
      <p class="date">2025-11-24</p>

      <small class="dont-index">Source: <a href="https://github.com/matthiaskloft/psychinterpreter/blob/HEAD/vignettes/articles/01-Getting_Started.qmd"><code>vignettes/articles/01-Getting_Started.qmd</code></a></small>
      <div class="d-none name"><code></code></div>
    </div>






    <section class="level2"><h2 id="what-is-psychinterpreter">What is psychinterpreter?<a class="anchor" aria-label="anchor" href="#what-is-psychinterpreter"></a>
</h2>
<p>The <strong>psychinterpreter</strong> package automatically interprets psychometric analysis results using <strong>Large Language Models (LLMs)</strong>. LLMs are AI systems (like ChatGPT, Claude, or open-source alternatives) that can understand and generate human-like text. Instead of manually examining complex statistical output and guessing what patterns represent, you get clear, human-readable interpretations and actionable insights.</p>
<p>The package also provides <strong>variable labeling</strong> functionality to generate short, descriptive labels from variable descriptions, making your data and results more readable.</p>
<p><strong>Currently supported analyses:</strong></p>
<ul>
<li>
<strong>Factor Analysis</strong> - Interpret factor loadings and suggest meaningful factor names</li>
</ul>
<p><strong>Planned analysis classes:</strong></p>
<ul>
<li>Gaussian Mixture Models - Interpret cluster profiles</li>
<li>Item Response Theory (IRT) - Interpret item diagnostics</li>
<li>Cognitive Diagnostic Models (CDM) - Interpret Q-matrix patterns</li>
</ul>
<p><strong>Use this package when you:</strong></p>
<ul>
<li>Have run a psychometric analysis (e.g., factor analysis, clustering)</li>
<li>Want automated, data-driven interpretations of your results</li>
<li>Need to quickly understand complex patterns in your data</li>
</ul></section><section class="level2"><h2 id="what-you-need">What You Need<a class="anchor" aria-label="anchor" href="#what-you-need"></a>
</h2>
<p>Before starting, make sure you have:</p>
<ol type="1">
<li>
<strong>Analysis results</strong> - from <code><a href="https://rdrr.io/pkg/psych/man/fa.html" class="external-link">psych::fa()</a></code>, <code><a href="https://rdrr.io/pkg/lavaan/man/efa.html" class="external-link">lavaan::efa()</a></code>, or similar functions</li>
<li>
<strong>Variable descriptions</strong> - brief explanations of what each variable measures</li>
<li>
<strong>A language model</strong> - we recommend <a href="https://ollama.com/" class="external-link">Ollama</a> (free, runs locally, offers cloud-powered models if you have an Ollama account)</li>
</ol></section><section class="level2"><h2 id="quick-start-example">Quick Start Example<a class="anchor" aria-label="anchor" href="#quick-start-example"></a>
</h2>
<p>Here’s a complete workflow for <strong>factor analysis</strong> using Big Five personality data in just a few lines:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://matthiaskloft.github.io/psychinterpreter/" class="external-link">psychinterpreter</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://personality-project.org/r/psych/" class="external-link">psych</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://hauselin.github.io/ollama-r/" class="external-link">ollamar</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 1. Describe your variables</span></span>
<span><span class="va">var_info</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span></span>
<span>  variable <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"A1"</span>, <span class="st">"A2"</span>, <span class="st">"A3"</span>, <span class="va">...</span><span class="op">)</span>,</span>
<span>  description <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"Am indifferent to others"</span>, <span class="st">"Inquire about others"</span>, <span class="va">...</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 2. Generate short labels (optional)</span></span>
<span><span class="va">labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/label_variables.html">label_variables</a></span><span class="op">(</span></span>
<span>  variable_info <span class="op">=</span> <span class="va">var_info</span>,</span>
<span>  llm_provider <span class="op">=</span> <span class="st">"ollama"</span>,</span>
<span>  llm_model <span class="op">=</span> <span class="st">"gpt-oss:20b-cloud"</span>,</span>
<span>  max_words <span class="op">=</span> <span class="fl">3</span>,</span>
<span>  case <span class="op">=</span> <span class="st">"title"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 3. Run factor analysis</span></span>
<span><span class="va">fa_result</span> <span class="op">&lt;-</span> <span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/fa.html" class="external-link">fa</a></span><span class="op">(</span><span class="va">bfi</span><span class="op">[</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">25</span><span class="op">]</span>, nfactors <span class="op">=</span> <span class="fl">5</span>, rotate <span class="op">=</span> <span class="st">"oblimin"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 4. Get LLM interpretation</span></span>
<span><span class="va">interpretation</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/interpret.html">interpret</a></span><span class="op">(</span></span>
<span>  fit_results <span class="op">=</span> <span class="va">fa_result</span>,</span>
<span>  variable_info <span class="op">=</span> <span class="va">var_info</span>,</span>
<span>  llm_provider <span class="op">=</span> <span class="st">"ollama"</span>,</span>
<span>  llm_model <span class="op">=</span> <span class="st">"gpt-oss:20b-cloud"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 5. View results</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">interpretation</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">interpretation</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section><section class="level2"><h2 id="step-by-step-tutorial-factor-analysis">Step-by-Step Tutorial: Factor Analysis<a class="anchor" aria-label="anchor" href="#step-by-step-tutorial-factor-analysis"></a>
</h2>
<p>This tutorial demonstrates the package using <strong>factor analysis</strong>, but the same workflow applies to other analysis types when they become available.</p>
<p>Let’s walk through a complete example using the Big Five Inventory (BFI) personality data.</p>
<section class="level3"><h3 id="setup">Setup<a class="anchor" aria-label="anchor" href="#setup"></a>
</h3>
<p>Load the packages we’ll need:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Install pacman if needed for easy package loading</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">require</a></span><span class="op">(</span><span class="st"><a href="https://github.com/trinker/pacman" class="external-link">"pacman"</a></span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html" class="external-link">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Load packages</span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html" class="external-link">p_load</a></span><span class="op">(</span></span>
<span>  <span class="st">"psychinterpreter"</span>,  <span class="co"># This package</span></span>
<span>  <span class="st">"psych"</span>,             <span class="co"># For factor analysis</span></span>
<span>  <span class="st">"reactable"</span>,         <span class="co"># For nice tables</span></span>
<span>  <span class="st">"dplyr"</span>,             <span class="co"># For data manipulation</span></span>
<span>  <span class="st">"pander"</span>             <span class="co"># package for pretty printing</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section><section class="level3"><h3 id="load-and-prepare-data">Load and Prepare Data<a class="anchor" aria-label="anchor" href="#load-and-prepare-data"></a>
</h3>
<p>The BFI dataset contains 25 personality items measuring the Big Five traits.</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Load Big Five Inventory data</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="st">"bfi"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="st">"bfi.dictionary"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Keep only the 25 personality items (remove demographics)</span></span>
<span><span class="va">bfi_items</span> <span class="op">&lt;-</span> <span class="va">bfi</span><span class="op">[</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">25</span><span class="op">]</span></span>
<span><span class="va">bfi_dict</span> <span class="op">&lt;-</span> <span class="va">bfi.dictionary</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="fl">25</span>, <span class="op">]</span></span></code></pre></div>
</details>
</div>
<p>Here’s what the data looks like:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">bfi_items</span>, <span class="fl">5</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html" class="external-link">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-acb80497c5188f5eb1b8" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-acb80497c5188f5eb1b8">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"A1":[2,2,5,4,2],"A2":[4,4,4,4,3],"A3":[3,5,5,6,3],"A4":[4,2,4,5,4],"A5":[4,5,4,5,5],"C1":[2,5,4,4,4],"C2":[3,4,5,4,4],"C3":[3,4,4,3,5],"C4":[4,3,2,5,3],"C5":[4,4,5,5,2],"E1":[3,1,2,5,2],"E2":[3,1,4,3,2],"E3":[3,6,4,4,5],"E4":[4,4,4,4,4],"E5":[4,3,5,4,5],"N1":[3,3,4,2,2],"N2":[4,3,5,5,3],"N3":[2,3,4,2,4],"N4":[2,5,2,4,4],"N5":[3,5,3,1,3],"O1":[3,4,4,3,3],"O2":[6,2,2,3,3],"O3":[3,4,5,4,4],"O4":[4,3,5,3,3],"O5":[3,3,2,5,3]},"columns":[{"id":"A1","name":"A1","type":"numeric"},{"id":"A2","name":"A2","type":"numeric"},{"id":"A3","name":"A3","type":"numeric"},{"id":"A4","name":"A4","type":"numeric"},{"id":"A5","name":"A5","type":"numeric"},{"id":"C1","name":"C1","type":"numeric"},{"id":"C2","name":"C2","type":"numeric"},{"id":"C3","name":"C3","type":"numeric"},{"id":"C4","name":"C4","type":"numeric"},{"id":"C5","name":"C5","type":"numeric"},{"id":"E1","name":"E1","type":"numeric"},{"id":"E2","name":"E2","type":"numeric"},{"id":"E3","name":"E3","type":"numeric"},{"id":"E4","name":"E4","type":"numeric"},{"id":"E5","name":"E5","type":"numeric"},{"id":"N1","name":"N1","type":"numeric"},{"id":"N2","name":"N2","type":"numeric"},{"id":"N3","name":"N3","type":"numeric"},{"id":"N4","name":"N4","type":"numeric"},{"id":"N5","name":"N5","type":"numeric"},{"id":"O1","name":"O1","type":"numeric"},{"id":"O2","name":"O2","type":"numeric"},{"id":"O3","name":"O3","type":"numeric"},{"id":"O4","name":"O4","type":"numeric"},{"id":"O5","name":"O5","type":"numeric"}],"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"89fa9d3c7f1a02b659920ed2c054436c"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>And here are the item descriptions:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bfi_dict</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">Item</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html" class="external-link">as.data.frame</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span>, defaultPageSize <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-85183fd8922dc33d9a9e" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-85183fd8922dc33d9a9e">{"x":{"tag":{"name":"Reactable","attribs":{"data":{".rownames":["A1","A2","A3","A4","A5","C1","C2","C3","C4","C5","E1","E2","E3","E4","E5","N1","N2","N3","N4","N5","O1","O2","O3","O4","O5"],"Item":["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time.","Don't talk a lot.","Find it difficult to approach others.","Know how to captivate people.","Make friends easily.","Take charge.","Get angry easily.","Get irritated easily.","Have frequent mood swings.","Often feel blue.","Panic easily.","Am full of ideas.","Avoid difficult reading material.","Carry the conversation to a higher level.","Spend time reflecting on things.","Will not probe deeply into a subject."]},"columns":[{"id":".rownames","name":"","type":"character","sortable":false,"filterable":false,"rowHeader":true},{"id":"Item","name":"Item","type":"factor"}],"defaultPageSize":10,"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"29737619662433573acb61817ce8aadf"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section><section class="level3"><h3 id="prepare-variable-descriptions">Prepare Variable Descriptions<a class="anchor" aria-label="anchor" href="#prepare-variable-descriptions"></a>
</h3>
<p>Create a data frame mapping variable names to their descriptions:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">variable_info</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span></span>
<span>  variable <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html" class="external-link">rownames</a></span><span class="op">(</span><span class="va">bfi_dict</span><span class="op">)</span>,</span>
<span>  description <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html" class="external-link">as.character</a></span><span class="op">(</span><span class="va">bfi_dict</span><span class="op">$</span><span class="va">Item</span><span class="op">)</span>,</span>
<span>  stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">variable_info</span>, <span class="fl">10</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-c10ee36280402e29f4b9" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-c10ee36280402e29f4b9">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"variable":["A1","A2","A3","A4","A5","C1","C2","C3","C4","C5"],"description":["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time."]},"columns":[{"id":"variable","name":"variable","type":"character"},{"id":"description","name":"description","type":"character"}],"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"fe2beeb9783cb57c310dc922a97838ce"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section><section class="level3"><h3 id="generate-short-variable-labels-optional">Generate Short Variable Labels (Optional)<a class="anchor" aria-label="anchor" href="#generate-short-variable-labels-optional"></a>
</h3>
<p>Before running the analysis, we can use LLMs to generate short, descriptive labels from our variable descriptions. This makes the analysis output and plots more readable:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">provider</span> <span class="op">&lt;-</span> <span class="st">"anthropic"</span></span>
<span><span class="va">llm</span> <span class="op">&lt;-</span> <span class="fu">ellmer</span><span class="fu">::</span><span class="fu"><a href="https://ellmer.tidyverse.org/reference/chat_anthropic.html" class="external-link">models_anthropic</a></span><span class="op">(</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span>,<span class="st">"id"</span><span class="op">]</span></span></code></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Generate short labels (1-3 words each)</span></span>
<span><span class="va">bfi_labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/label_variables.html">label_variables</a></span><span class="op">(</span></span>
<span>  variable_info <span class="op">=</span> <span class="va">variable_info</span>,</span>
<span>  llm_provider <span class="op">=</span> <span class="va">provider</span>,</span>
<span>  llm_model <span class="op">=</span> <span class="va">llm</span>,</span>
<span>  max_words <span class="op">=</span> <span class="fl">3</span>,        <span class="co"># Keep labels concise</span></span>
<span>  sep <span class="op">=</span> <span class="st">"_"</span>,            <span class="co"># Use underscores between words</span></span>
<span>  case <span class="op">=</span> <span class="st">"title"</span>        <span class="co"># Title Case format</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<p>Now replace the original variable names with these short labels:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create new variable names combining original names with labels</span></span>
<span><span class="va">labels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html" class="external-link">paste</a></span><span class="op">(</span></span>
<span>  <span class="va">bfi_labels</span><span class="op">$</span><span class="va">labels_formatted</span><span class="op">$</span><span class="va">variable</span>,</span>
<span>  <span class="va">bfi_labels</span><span class="op">$</span><span class="va">labels_formatted</span><span class="op">$</span><span class="va">label</span>,</span>
<span>  sep <span class="op">=</span> <span class="st">"-"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Apply to data and variable_info</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">bfi_items</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">labels</span></span>
<span><span class="va">variable_info</span><span class="op">$</span><span class="va">variable</span> <span class="op">&lt;-</span> <span class="va">labels</span></span>
<span></span>
<span><span class="co"># Show updated variable info</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html" class="external-link">head</a></span><span class="op">(</span><span class="va">variable_info</span>, <span class="fl">10</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-a50c13e4e3e242e0fc60" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-a50c13e4e3e242e0fc60">{"x":{"tag":{"name":"Reactable","attribs":{"data":{"variable":["A1-Indifferent_To_Others","A2-Inquire_Well-Being","A3-Comfort_Others","A4-Love_Children","A5-Put_At_Ease","C1-Exacting_Work","C2-Perfectionist","C3-Plan-Oriented","C4-Half-Way_Effort","C5-Waste_Time"],"description":["Am indifferent to the feelings of others.","Inquire about others' well-being.","Know how to comfort others.","Love children.","Make people feel at ease.","Am exacting in my work.","Continue until everything is perfect.","Do things according to a plan.","Do things in a half-way manner.","Waste my time."]},"columns":[{"id":"variable","name":"variable","type":"character"},{"id":"description","name":"description","type":"character"}],"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"8b3d16d8b3198c549bc220443e562ff8"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div>
<blockquote>
<p><strong>Tip</strong></p>
<p><strong>Label Formatting Options</strong></p>
<p>The <code><a href="../reference/label_variables.html">label_variables()</a></code> function offers extensive formatting control:</p>
<ul>
<li>
<strong>Label types</strong>: <code>label_type = "short"</code> (1-3 words), <code>"phrase"</code> (4-7 words), <code>"acronym"</code> (3-5 chars)</li>
<li>
<strong>Case transformations</strong>: <code>case = "snake"</code>, <code>"camel"</code>, <code>"title"</code>, <code>"upper"</code>, etc.</li>
<li>
<strong>Simplification</strong>: <code>remove_articles = TRUE</code>, <code>remove_prepositions = TRUE</code>, <code>abbreviate = TRUE</code>
</li>
<li>
<strong>Reformatting</strong>: Use <code><a href="../reference/reformat_labels.html">reformat_labels()</a></code> to change formatting without calling the LLM again</li>
</ul>
<p>See <code><a href="../reference/label_variables.html">?label_variables</a></code> for all options.</p>
</blockquote>
</div>
</section><section class="level3"><h3 id="run-factor-analysis">Run Factor Analysis<a class="anchor" aria-label="anchor" href="#run-factor-analysis"></a>
</h3>
<p>Now perform a standard exploratory factor analysis with 5 factors using the labeled data:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">fa_result</span> <span class="op">&lt;-</span> <span class="fu">psych</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/psych/man/fa.html" class="external-link">fa</a></span><span class="op">(</span></span>
<span>  <span class="va">bfi_items</span>,  <span class="co"># Now contains labeled variables</span></span>
<span>  nfactors <span class="op">=</span> <span class="fl">5</span>,</span>
<span>  rotate <span class="op">=</span> <span class="st">"oblimin"</span>,  <span class="co"># Oblique rotation</span></span>
<span>  fm <span class="op">=</span> <span class="st">"ml"</span>            <span class="co"># Maximum likelihood</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<p>View the factor loadings (now with readable labels):</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Extract and display loadings</span></span>
<span><span class="va">loadings_matrix</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/class.html" class="external-link">unclass</a></span><span class="op">(</span><span class="va">fa_result</span><span class="op">$</span><span class="va">loadings</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html" class="external-link">as.data.frame</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="va">loadings_matrix</span>, <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-d86d3a62ef5e9ceed93c" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-d86d3a62ef5e9ceed93c">{"x":{"tag":{"name":"Reactable","attribs":{"data":{".rownames":["A1-Indifferent_To_Others","A2-Inquire_Well-Being","A3-Comfort_Others","A4-Love_Children","A5-Put_At_Ease","C1-Exacting_Work","C2-Perfectionist","C3-Plan-Oriented","C4-Half-Way_Effort","C5-Waste_Time","E1-Quiet","E2-Difficulty_Approaching","E3-Captivate_People","E4-Make_Friends_Easily","E5-Take_Charge","N1-Anger_Proneness","N2-Irritability","N3-Mood_Swings","N4-Depressive_Mood","N5-Panic_Proneness","O1-Full_Of_Ideas","O2-Avoid_Complex_Reading","O3-Deep_Conversation","O4-Reflective","O5-Avoid_Deep_Probing"],"ML2":[0.2,-0.02,-0.03,-0.06,-0.14,0.06,0.13,0.04,0.12,0.14,-0.09,0.06,0.06,0,0.18,0.85,0.82,0.67,0.41,0.44,-0.01,0.16,0.01,0.08,0.11],"ML5":[-0.36,0.6,0.67,0.46,0.58,-0,0.11,0.11,0.06,0.01,-0.1,-0.09,0.3,0.36,0.08,-0.09,-0.08,0.1,0.09,0.22,0.02,0.21,0.09,0.14,0.1],"ML1":[-0.14,0.01,-0.07,-0.04,-0.17,0.05,0.13,0.08,0.04,0.16,0.56,0.67,-0.34,-0.53,-0.39,-0.09,-0.04,0.14,0.42,0.25,-0.06,-0.03,-0.1,0.36,-0.07],"ML3":[0.04,0.09,0.03,0.2,-0,0.53,0.64,0.56,-0.64,-0.57,0.1,-0.03,-0.02,0.01,0.27,0.01,0.02,-0.06,-0.16,-0.02,0.06,-0.1,0,-0.04,-0.05],"ML4":[-0.04,0.03,0.04,-0.15,0.06,0.16,0.06,-0.06,-0.03,0.1,-0.11,-0.07,0.31,-0.05,0.22,-0.05,0.01,0.03,0.08,-0.14,0.53,-0.44,0.63,0.38,-0.52]},"columns":[{"id":".rownames","name":"","type":"character","sortable":false,"filterable":false,"rowHeader":true},{"id":"ML2","name":"ML2","type":"numeric"},{"id":"ML5","name":"ML5","type":"numeric"},{"id":"ML1","name":"ML1","type":"numeric"},{"id":"ML3","name":"ML3","type":"numeric"},{"id":"ML4","name":"ML4","type":"numeric"}],"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"1e7ac4313ea6afc3e3aed403a13903cb"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section><section class="level3"><h3 id="get-llm-interpretation">Get LLM Interpretation<a class="anchor" aria-label="anchor" href="#get-llm-interpretation"></a>
</h3>
<p>Now use <code><a href="../reference/interpret.html">interpret()</a></code> to get automatic factor interpretations:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">interpretation</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/interpret.html">interpret</a></span><span class="op">(</span></span>
<span>  fit_results <span class="op">=</span> <span class="va">fa_result</span>,</span>
<span>  variable_info <span class="op">=</span> <span class="va">variable_info</span>,</span>
<span>  llm_provider <span class="op">=</span> <span class="va">provider</span>,</span>
<span>  llm_model <span class="op">=</span> <span class="va">llm</span>,</span>
<span>  silent <span class="op">=</span> <span class="fl">1</span>  <span class="co"># Will print explicitly below</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<div>
<blockquote>
<p><strong>Note</strong></p>
<p><strong>First time using Ollama?</strong></p>
<ol type="1">
<li>Install Ollama from <a href="https://ollama.com/" class="external-link">ollama.com</a> and the <code>ollamar</code> package: <code>install.packages("ollamar")</code>
</li>
<li>Pull the model: <code>ollamar::pull("gpt-oss:20b-cloud")</code>
</li>
<li>Start the Ollama server before running <code><a href="../reference/interpret.html">interpret()</a></code>
</li>
</ol>
</blockquote>
</div>
</section><section class="level3"><h3 id="view-results">View Results<a class="anchor" aria-label="anchor" href="#view-results"></a>
</h3>
<p>Print the interpretation report:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">interpretation</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>FACTOR ANALYSIS INTERPRETATION
────────────────────────────────────────────────────────────────────────────────

Number of factors: 5
Loading cutoff: 0.3
LLM used: anthropic - claude-haiku-4-5-20251001
Tokens:
  Input: 0
  Output: 0
Elapsed time: 10.7

SUGGESTED FACTOR NAMES
────────────────────────────────────────────────────────────────────────────────

• Factor 1 (10%): Emotional Instability
• Factor 2 (8.4%): Empathic Concern
• Factor 3 (8.3%): Social Withdrawal
• Factor 4 (8.2%): Conscientious Organization
• Factor 5 (6.6%): Intellectual Engagement

Total variance explained: 41.4%

FACTOR CORRELATIONS
────────────────────────────────────────────────────────────────────────────────

ML2: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01
ML5: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23
ML1: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17
ML3: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20
ML4: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

DETAILED FACTOR INTERPRETATIONS
────────────────────────────────────────────────────────────────────────────────

Factor 1 (ML2) - Emotional Instability
Number of significant loadings: 5
Variance explained: 9.96%
Factor Correlations: ML5 = -.03, ML1 = .23, ML3 = -.21, ML4 = -.01

Variables:
  1. N1-Anger_Proneness, Get angry easily. (Positive, Very Strong, .852)
  2. N2-Irritability, Get irritated easily. (Positive, Very Strong, .817)
  3. N3-Mood_Swings, Have frequent mood swings. (Positive, Strong, .665)
  4. N5-Panic_Proneness, Panic easily. (Positive, Moderate, .439)
  5. N4-Depressive_Mood, Often feel blue. (Positive, Moderate, .413)

LLM Interpretation:
This factor represents neuroticism and emotional reactivity, capturing the
tendency toward negative affect and emotional dysregulation. Anger proneness
(0.852) and irritability (0.817) are the primary markers, with mood swings
(0.665), panic proneness (0.439), and depressive mood (0.413) providing
secondary indicators. The factor reflects a dispositional vulnerability to
experiencing intense, unstable emotions across various contexts. Individuals
high on this dimension report heightened emotional reactivity, difficulty
managing negative affect, and susceptibility to anxiety and depressive symptoms.
The construct demonstrates strong convergent validity through intercorrelated
negative emotional states.

════════════════════════════════════════════════════════════════════════════════

Factor 2 (ML5) - Empathic Concern
Number of significant loadings: 7
Variance explained: 8.41%
Factor Correlations: ML2 = -.03, ML1 = -.31, ML3 = .20, ML4 = .23

Variables:
  1. A3-Comfort_Others, Know how to comfort others. (Positive, Strong, .668)
  2. A2-Inquire_Well-Being, Inquire about others' well-being. (Positive, Strong,
  .603)
  3. A5-Put_At_Ease, Make people feel at ease. (Positive, Strong, .577)
  4. A4-Love_Children, Love children. (Positive, Moderate, .456)
  5. E4-Make_Friends_Easily, Make friends easily. (Positive, Moderate, .362)
  6. A1-Indifferent_To_Others, Am indifferent to the feelings of others.
  (Negative, Moderate, -.360)
  7. E3-Captivate_People, Know how to captivate people. (Positive, Moderate,
  .303)

LLM Interpretation:
This factor measures interpersonal warmth and empathic responsiveness,
characterized by genuine concern for others' emotional states and comfort.
Strong loadings on comfort others (0.668), inquire well-being (0.603), and put
at ease (0.577) indicate prosocial and nurturing tendencies. The negative
loading on indifference (−0.360) reinforces orientation toward others' needs.
Secondary loadings on make friends easily (0.362) and captivate people (0.303)
suggest interpersonal facilitation. Notably, love children (0.456) reflects
compassion toward vulnerable populations. This factor represents agreeableness
and empathy, demonstrating convergent validity through theoretically coherent
emotional and social variables.

════════════════════════════════════════════════════════════════════════════════

Factor 3 (ML1) - Social Withdrawal
Number of significant loadings: 7
Variance explained: 8.28%
Factor Correlations: ML2 = .23, ML5 = -.31, ML3 = -.22, ML4 = -.17

Variables:
  1. E2-Difficulty_Approaching, Find it difficult to approach others. (Positive,
  Strong, .667)
  2. E1-Quiet, Don't talk a lot. (Positive, Strong, .565)
  3. E4-Make_Friends_Easily, Make friends easily. (Negative, Strong, -.527)
  4. N4-Depressive_Mood, Often feel blue. (Positive, Moderate, .420)
  5. E5-Take_Charge, Take charge. (Negative, Moderate, -.394)
  6. O4-Reflective, Spend time reflecting on things. (Positive, Moderate, .357)
  7. E3-Captivate_People, Know how to captivate people. (Negative, Moderate,
  -.341)

LLM Interpretation:
This factor captures introversion and social inhibition, defined by difficulty
in interpersonal engagement and avoidance of social interaction. Difficulty
approaching others (0.667) and quietness (0.565) are primary indicators of
social hesitance, with strong negative loadings on social facilitation: make
friends easily (−0.527), take charge (−0.394), and captivate people (−0.341).
Secondary loadings on depressive mood (0.420) and reflective (0.357) suggest
accompanying introspection or withdrawal-related mood. This factor represents
the introverted end of extraversion, distinct from social competence. The
pattern demonstrates discriminant validity from empathy, measuring behavioral
social inhibition rather than emotional warmth.

════════════════════════════════════════════════════════════════════════════════

Factor 4 (ML3) - Conscientious Organization
Number of significant loadings: 5
Variance explained: 8.19%
Factor Correlations: ML2 = -.21, ML5 = .20, ML1 = -.22, ML4 = .20

Variables:
  1. C4-Half-Way_Effort, Do things in a half-way manner. (Negative, Strong,
  -.643)
  2. C2-Perfectionist, Continue until everything is perfect. (Positive, Strong,
  .638)
  3. C5-Waste_Time, Waste my time. (Negative, Strong, -.570)
  4. C3-Plan-Oriented, Do things according to a plan. (Positive, Strong, .564)
  5. C1-Exacting_Work, Am exacting in my work. (Positive, Strong, .532)

LLM Interpretation:
This factor reflects conscientiousness and organized goal-directedness through
achievement-oriented and systematic behaviors. Perfectionism (0.638), exacting
work standards (0.532), and plan-oriented approaches (0.564) represent the core
construct. Notably, the strong negative loadings on half-way effort (−0.643) and
wasting time (−0.570) demonstrate disciplined commitment and efficiency.
Secondary positive loading on take charge (0.274) suggests assertive
implementation of standards. The factor captures meticulous, organized
personality traits driving task completion and quality outcomes. Convergent
validity is demonstrated through theoretically consistent work ethic and
discipline indicators, complementing but remaining distinct from other
personality dimensions.

════════════════════════════════════════════════════════════════════════════════

Factor 5 (ML4) - Intellectual Engagement
Number of significant loadings: 6
Variance explained: 6.57%
Factor Correlations: ML2 = -.01, ML5 = .23, ML1 = -.17, ML3 = .20

Variables:
  1. O3-Deep_Conversation, Carry the conversation to a higher level. (Positive,
  Strong, .633)
  2. O1-Full_Of_Ideas, Am full of ideas. (Positive, Strong, .534)
  3. O5-Avoid_Deep_Probing, Will not probe deeply into a subject. (Negative,
  Strong, -.522)
  4. O2-Avoid_Complex_Reading, Avoid difficult reading material. (Negative,
  Moderate, -.441)
  5. O4-Reflective, Spend time reflecting on things. (Positive, Moderate, .379)
  6. E3-Captivate_People, Know how to captivate people. (Positive, Moderate,
  .315)

LLM Interpretation:
This factor represents openness to experience and cognitive curiosity,
emphasizing intellectual sophistication and reflective thinking. Deep
conversation (0.633) and full of ideas (0.534) indicate abstract thinking and
intellectual engagement. Notably, the strong negative loadings on avoid complex
reading (−0.441) and avoid deep probing (−0.522) demonstrate intellectual
approach rather than avoidance. Secondary loadings on reflective (0.379) and
captivate people (0.315) suggest analytical depth and communicative ability.
This factor captures openness-related intellectual curiosity and preference for
complex cognitive tasks. The construct demonstrates discriminant validity from
other factors, uniquely measuring cognitive engagement and intellectual
disposition.

════════════════════════════════════════════════════════════════════════════════

CROSS-LOADING VARIABLES
────────────────────────────────────────────────────────────────────────────────

Variables loading on multiple factors (&gt;= 0.3):
- E3-Captivate_People: ML5 (.303), ML1 (-.341), ML4 (.315)
- E4-Make_Friends_Easily: ML5 (.362), ML1 (-.527)
- N4-Depressive_Mood: ML2 (.413), ML1 (.420)
- O4-Reflective: ML1 (.357), ML4 (.379)</code></pre>
</div>
</div>
<p>The output shows: - Suggested factor names - Which variables load on each factor - A brief interpretation of what the factor represents</p>
<p>View suggested factor names:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">suggested_names</span> <span class="op">&lt;-</span> <span class="va">interpretation</span><span class="op">$</span><span class="va">suggested_names</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>Suggested_Factor_Name <span class="op">=</span> <span class="va">suggested_names</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">reactable</span><span class="op">(</span>striped <span class="op">=</span> <span class="cn">TRUE</span>, highlight <span class="op">=</span> <span class="cn">TRUE</span>, bordered <span class="op">=</span> <span class="cn">TRUE</span>, compact <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div class="reactable html-widget html-fill-item" id="htmlwidget-fbcd7a87f071e63cb28f" style="width:auto;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-fbcd7a87f071e63cb28f">{"x":{"tag":{"name":"Reactable","attribs":{"data":{".rownames":["ML2","ML5","ML1","ML3","ML4"],"Suggested_Factor_Name":["Emotional Instability","Empathic Concern","Social Withdrawal","Conscientious Organization","Intellectual Engagement"]},"columns":[{"id":".rownames","name":"","type":"character","sortable":false,"filterable":false,"rowHeader":true},{"id":"Suggested_Factor_Name","name":"Suggested_Factor_Name","type":"character"}],"highlight":true,"bordered":true,"striped":true,"compact":true,"dataKey":"31070335ad05cd68e7568b7fd517587d"},"children":[]},"class":"reactR_markup"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section><section class="level3"><h3 id="visualize-factor-structure">Visualize Factor Structure<a class="anchor" aria-label="anchor" href="#visualize-factor-structure"></a>
</h3>
<p>Create a visual representation of the factor loadings:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html" class="external-link">plot</a></span><span class="op">(</span><span class="va">interpretation</span>, cutoff <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<div>
<figure><p><img src="01-Getting_Started_files/figure-html/plot-loadings-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows which variables load strongly on each factor, making it easy to see the factor structure at a glance.</p>
</section><section class="level3"><h3 id="export-results">Export Results<a class="anchor" aria-label="anchor" href="#export-results"></a>
</h3>
<p>Save your interpretation to a file:</p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Export as markdown</span></span>
<span><span class="fu"><a href="../reference/export_interpretation.html">export_interpretation</a></span><span class="op">(</span></span>
<span>  <span class="va">interpretation</span>,</span>
<span>  format <span class="op">=</span> <span class="st">"md"</span>,</span>
<span>  file <span class="op">=</span> <span class="st">"bfi_interpretation"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Export as plain text</span></span>
<span><span class="fu"><a href="../reference/export_interpretation.html">export_interpretation</a></span><span class="op">(</span></span>
<span>  <span class="va">interpretation</span>,</span>
<span>  format <span class="op">=</span> <span class="st">"txt"</span>,</span>
<span>  file <span class="op">=</span> <span class="st">"bfi_interpretation"</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details>
</div>
</section></section><section class="level2"><h2 id="customizing-your-interpretation">Customizing Your Interpretation<a class="anchor" aria-label="anchor" href="#customizing-your-interpretation"></a>
</h2>
<p>You can control several aspects of the interpretation:</p>
<p><strong>Key parameters:</strong></p>
<ul>
<li>
<code>cutoff</code>: Threshold for displaying results (e.g., minimum loading for FA)</li>
<li>
<code>hide_low_loadings</code>: Whether to hide loadings below the cutoff from the LLM</li>
<li>
<code>word_limit</code>: Control how verbose the LLM interpretations are</li>
<li>
<code>output_format</code>: Choose between plain text or markdown formatting</li>
<li>
<code>heading_level</code>: Heading level to start the report with.</li>
</ul>
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">interpretation</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/interpret.html">interpret</a></span><span class="op">(</span></span>
<span>  fit_results <span class="op">=</span> <span class="va">fa_result</span>,</span>
<span>  variable_info <span class="op">=</span> <span class="va">variable_info</span>,</span>
<span>  llm_provider <span class="op">=</span> <span class="va">provider</span>,</span>
<span>  llm_model <span class="op">=</span> <span class="va">llm</span>,</span>
<span></span>
<span>  cutoff <span class="op">=</span> <span class="fl">0.4</span>,              <span class="co"># Threshold for including results (default: 0.3)</span></span>
<span>  hide_low_loadings <span class="op">=</span> <span class="cn">TRUE</span>,  <span class="co"># hide low loadings below cutoff from the LLM</span></span>
<span>  word_limit <span class="op">=</span> <span class="fl">30</span>,          <span class="co"># Max words per interpretation (default: 150)</span></span>
<span>  output_format <span class="op">=</span> <span class="st">"markdown"</span>,<span class="co"># Output format: "text" or "markdown"</span></span>
<span>  heading_level <span class="op">=</span> <span class="fl">3</span>,         <span class="co"># set heading level for markdown output</span></span>
<span><span class="op">)</span></span></code></pre></div>
</details><section class="level3"><h3 id="factor-analysis-interpretation">FACTOR ANALYSIS INTERPRETATION<a class="anchor" aria-label="anchor" href="#factor-analysis-interpretation"></a>
</h3>
<p><strong>Number of factors:</strong> 5<br><strong>Loading cutoff:</strong> 0.4<br><strong>LLM used:</strong> anthropic - claude-haiku-4-5-20251001<br><strong>Tokens:</strong><br>
Input: 0<br>
Output: 0<br><strong>Elapsed time:</strong> 5.9</p>
<section class="level4"><h4 id="suggested-factor-names">SUGGESTED FACTOR NAMES<a class="anchor" aria-label="anchor" href="#suggested-factor-names"></a>
</h4>
<ul>
<li>
<strong>Factor 1 (10%):</strong> <em>Negative Emotionality</em>
</li>
<li>
<strong>Factor 2 (8.4%):</strong> <em>Empathic Concern</em>
</li>
<li>
<strong>Factor 3 (8.3%):</strong> <em>Social Introversion</em>
</li>
<li>
<strong>Factor 4 (8.2%):</strong> <em>Conscientiousness</em>
</li>
<li>
<strong>Factor 5 (6.6%):</strong> <em>Openness to Experience</em>
</li>
</ul>
<p><strong>Total variance explained by all factors: 41.4%</strong></p>
</section><section class="level4"><h4 id="factor-correlations">FACTOR CORRELATIONS<a class="anchor" aria-label="anchor" href="#factor-correlations"></a>
</h4>
<ul>
<li>
<strong>ML2:</strong> ML5 = -.03, ML1 = .23, ML3 = -.21,<br>
ML4 = -.01</li>
<li>
<strong>ML5:</strong> ML2 = -.03, ML1 = -.31, ML3 = .20,<br>
ML4 = .23</li>
<li>
<strong>ML1:</strong> ML2 = .23, ML5 = -.31, ML3 = -.22,<br>
ML4 = -.17</li>
<li>
<strong>ML3:</strong> ML2 = -.21, ML5 = .20, ML1 = -.22,<br>
ML4 = .20</li>
<li>
<strong>ML4:</strong> ML2 = -.01, ML5 = .23, ML1 = -.17,<br>
ML3 = .20</li>
</ul></section><section class="level4"><h4 id="detailed-factor-interpretations">DETAILED FACTOR INTERPRETATIONS<a class="anchor" aria-label="anchor" href="#detailed-factor-interpretations"></a>
</h4>
<section class="level5"><h5 id="factor-1-ml2-negative-emotionality">Factor 1 (ML2): Negative Emotionality<a class="anchor" aria-label="anchor" href="#factor-1-ml2-negative-emotionality"></a>
</h5>
<p><strong>Number of significant loadings:</strong> 5<br><strong>Variance explained:</strong> 9.96%<br><strong>Factor Correlations:</strong> ML5 = -.03, ML1 = .23, ML3 = -.21,</p>
<p>ML4 = -.01</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>N1-Anger_Proneness, Get angry easily. (Positive, Very Strong, .852)</li>
<li>N2-Irritability, Get irritated easily. (Positive, Very Strong, .817)</li>
<li>N3-Mood_Swings, Have frequent mood swings. (Positive, Strong, .665)</li>
<li>N5-Panic_Proneness, Panic easily. (Positive, Moderate, .439)</li>
<li>N4-Depressive_Mood, Often feel blue. (Positive, Moderate, .413)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Captures tendency toward anger, irritability, and mood instability. Strong loadings on anger proneness and irritability reflect dispositional negative affect. Weaker panic and depression loadings suggest broader emotional dysregulation. Essentially measures proneness to negative emotional experiences.</p>
</section><section class="level5"><h5 id="factor-2-ml5-empathic-concern">Factor 2 (ML5): Empathic Concern<a class="anchor" aria-label="anchor" href="#factor-2-ml5-empathic-concern"></a>
</h5>
<p><strong>Number of significant loadings:</strong> 4<br><strong>Variance explained:</strong> 8.41%<br><strong>Factor Correlations:</strong> ML2 = -.03, ML1 = -.31, ML3 = .20,</p>
<p>ML4 = .23</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>A3-Comfort_Others, Know how to comfort others. (Positive, Strong, .668)</li>
<li>A2-Inquire_Well-Being, Inquire about others’ well-being. (Positive, Strong, .603)</li>
<li>A5-Put_At_Ease, Make people feel at ease. (Positive, Strong, .577)</li>
<li>A4-Love_Children, Love children. (Positive, Moderate, .456)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Reflects genuine care for others’ wellbeing through comfort provision and interpersonal warmth. Strong loadings on comforting others and inquiring about wellbeing demonstrate active empathic engagement. Slightly weaker affection toward children suggests the factor emphasizes demonstrated empathic behavior over general fondness.</p>
</section><section class="level5"><h5 id="factor-3-ml1-social-introversion">Factor 3 (ML1): Social Introversion<a class="anchor" aria-label="anchor" href="#factor-3-ml1-social-introversion"></a>
</h5>
<p><strong>Number of significant loadings:</strong> 4<br><strong>Variance explained:</strong> 8.28%<br><strong>Factor Correlations:</strong> ML2 = .23, ML5 = -.31, ML3 = -.22,</p>
<p>ML4 = -.17</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>E2-Difficulty_Approaching, Find it difficult to approach others. (Positive, Strong, .667)</li>
<li>E1-Quiet, Don’t talk a lot. (Positive, Strong, .565)</li>
<li>E4-Make_Friends_Easily, Make friends easily. (Negative, Strong, -.527)</li>
<li>N4-Depressive_Mood, Often feel blue. (Positive, Moderate, .420)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Represents withdrawal from social interaction and difficulty initiating relationships. Strong loadings on approach difficulty and quietness reflect social hesitance. Negative loading on friend-making easily indicates inverse relationship. Modest depressive mood loading suggests emotional components accompanying social withdrawal.</p>
</section><section class="level5"><h5 id="factor-4-ml3-conscientiousness">Factor 4 (ML3): Conscientiousness<a class="anchor" aria-label="anchor" href="#factor-4-ml3-conscientiousness"></a>
</h5>
<p><strong>Number of significant loadings:</strong> 5<br><strong>Variance explained:</strong> 8.19%<br><strong>Factor Correlations:</strong> ML2 = -.21, ML5 = .20, ML1 = -.22,</p>
<p>ML4 = .20</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>C4-Half-Way_Effort, Do things in a half-way manner. (Negative, Strong, -.643)</li>
<li>C2-Perfectionist, Continue until everything is perfect. (Positive, Strong, .638)</li>
<li>C5-Waste_Time, Waste my time. (Negative, Strong, -.570)</li>
<li>C3-Plan-Oriented, Do things according to a plan. (Positive, Strong, .564)</li>
<li>C1-Exacting_Work, Am exacting in my work. (Positive, Strong, .532)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Reflects orderly, disciplined work orientation and task commitment. Strong perfectionism and planning loadings demonstrate conscientious trait manifestation. Negative loadings on half-way effort and time-wasting reinforce meticulous execution. Factor captures dedication to thorough, systematic task completion and personal accountability.</p>
</section><section class="level5"><h5 id="factor-5-ml4-openness-to-experience">Factor 5 (ML4): Openness to Experience<a class="anchor" aria-label="anchor" href="#factor-5-ml4-openness-to-experience"></a>
</h5>
<p><strong>Number of significant loadings:</strong> 4<br><strong>Variance explained:</strong> 6.57%<br><strong>Factor Correlations:</strong> ML2 = -.01, ML5 = .23, ML1 = -.17,</p>
<p>ML3 = .20</p>
<p><strong>Variables:</strong></p>
<ol type="1">
<li>O3-Deep_Conversation, Carry the conversation to a higher level. (Positive, Strong, .633)</li>
<li>O1-Full_Of_Ideas, Am full of ideas. (Positive, Strong, .534)</li>
<li>O5-Avoid_Deep_Probing, Will not probe deeply into a subject. (Negative, Strong, -.522)</li>
<li>O2-Avoid_Complex_Reading, Avoid difficult reading material. (Negative, Moderate, -.441)</li>
</ol>
<p><strong>LLM Interpretation:</strong><br>
Represents intellectual engagement and cognitive sophistication. Strong deep conversation loading reflects preference for substantive discourse. Positive idea generation and negative avoidance of complex reading demonstrate intellectual curiosity. Factor captures orientation toward intellectual stimulation and abstract thinking over concrete simplicity.</p>
</section></section><section class="level4"><h4 id="cross-loading-variables">CROSS-LOADING VARIABLES<a class="anchor" aria-label="anchor" href="#cross-loading-variables"></a>
</h4>
<p>Variables loading on multiple factors (&gt;= 0.4):</p>
<ul>
<li>
<strong>N4-Depressive_Mood</strong>: ML2 (.413), ML1 (.420)</li>
</ul></section><section class="level4"><h4 id="variables-not-covered-by-any-factor">VARIABLES NOT COVERED BY ANY FACTOR<a class="anchor" aria-label="anchor" href="#variables-not-covered-by-any-factor"></a>
</h4>
<p>Variables with no absolute loadings &gt;= 0.4 (highest absolute loading shown):</p>
<ul>
<li>
<strong>A1-Indifferent_To_Others</strong> (highest: ML5 = .360)</li>
<li>
<strong>E3-Captivate_People</strong> (highest: ML1 = .341)</li>
<li>
<strong>E5-Take_Charge</strong> (highest: ML1 = .394)</li>
<li>
<strong>O4-Reflective</strong> (highest: ML4 = .379)</li>
</ul></section></section></section><section class="level2"><h2 id="common-questions">Common Questions<a class="anchor" aria-label="anchor" href="#common-questions"></a>
</h2>
<p><strong>Q: What if the LLM interpretation seems wrong?</strong></p>
<p>The LLM bases interpretations on your variable descriptions and statistical results. You can:</p>
<ul>
<li>Provide better, more descriptive variable descriptions</li>
<li>Use a bigger LLM. Small models may struggle with the task and structured output requirements.</li>
<li>Adjust the <code>cutoff</code> and <code>hide_low_loadings</code> parameters to change which results are included</li>
<li>Add context with the <code>additional_info</code> parameter</li>
</ul>
<p><strong>Q: Can I use different LLMs?</strong></p>
<p>Yes! The package supports all providers supported by the <a href="https://ellmer.tidyverse.org/" class="external-link"><code>ellmer</code></a> package, for example:</p>
<ul>
<li>
<strong>Ollama</strong> (local, free): <code>llm_provider = "ollama"</code>
</li>
<li>
<strong>OpenAI</strong> (API key required): <code>llm_provider = "openai"</code>
</li>
<li>
<strong>Anthropic Claude</strong> (API key required): <code>llm_provider = "anthropic"</code>
</li>
</ul>
<p><strong>Q: How do I set API keys for OpenAI or Anthropic?</strong></p>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Add to your .Renviron file:</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Sys.setenv.html" class="external-link">Sys.setenv</a></span><span class="op">(</span>OPENAI_API_KEY <span class="op">=</span> <span class="st">"your-key-here"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Sys.setenv.html" class="external-link">Sys.setenv</a></span><span class="op">(</span>ANTHROPIC_API_KEY <span class="op">=</span> <span class="st">"your-key-here"</span><span class="op">)</span></span></code></pre></div>
</details>
</div>
<p>Also refer to the documentation of the <code>ellmer</code> <a href="https://ellmer.tidyverse.org/" class="external-link">https://ellmer.tidyverse.org/</a> package.</p>
</section><section class="level2"><h2 id="session-info">Session Info<a class="anchor" aria-label="anchor" href="#session-info"></a>
</h2>
<div class="cell">
<details open="" class="code-fold"><summary>Code</summary><div class="sourceCode cell-code" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">pander</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pander/man/pander.html" class="external-link">pander</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html" class="external-link">sessionInfo</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</details><div class="cell-output-display">
<p><strong>R version 4.5.2 (2025-10-31 ucrt)</strong></p>
<p><strong>Platform:</strong> x86_64-w64-mingw32/x64</p>
<p><strong>locale:</strong> <em>LC_COLLATE=German_Germany.utf8</em>, <em>LC_CTYPE=German_Germany.utf8</em>, <em>LC_MONETARY=German_Germany.utf8</em>, <em>LC_NUMERIC=C</em> and <em>LC_TIME=German_Germany.utf8</em></p>
<p><strong>attached base packages:</strong> <em>stats</em>, <em>graphics</em>, <em>grDevices</em>, <em>utils</em>, <em>datasets</em>, <em>methods</em> and <em>base</em></p>
<p><strong>other attached packages:</strong> <em>pander(v.0.6.6)</em>, <em>dplyr(v.1.1.4)</em>, <em>reactable(v.0.4.4)</em>, <em>psych(v.2.5.6)</em>, <em>psychinterpreter(v.0.0.0.9000)</em> and <em>pacman(v.0.5.1)</em></p>
<p><strong>loaded via a namespace (and not attached):</strong> <em>gtable(v.0.3.6)</em>, <em>jsonlite(v.2.0.0)</em>, <em>compiler(v.4.5.2)</em>, <em>Rcpp(v.1.1.0)</em>, <em>tidyselect(v.1.2.1)</em>, <em>parallel(v.4.5.2)</em>, <em>tidyr(v.1.3.1)</em>, <em>scales(v.1.4.0)</em>, <em>yaml(v.2.3.10)</em>, <em>fastmap(v.1.2.0)</em>, <em>lattice(v.0.22-7)</em>, <em>ggplot2(v.4.0.1)</em>, <em>R6(v.2.6.1)</em>, <em>labeling(v.0.4.3)</em>, <em>generics(v.0.1.4)</em>, <em>curl(v.7.0.0)</em>, <em>httr2(v.1.2.1)</em>, <em>knitr(v.1.50)</em>, <em>htmlwidgets(v.1.6.4)</em>, <em>tibble(v.3.3.0)</em>, <em>ellmer(v.0.4.0)</em>, <em>pillar(v.1.11.1)</em>, <em>RColorBrewer(v.1.1-3)</em>, <em>rlang(v.1.1.6)</em>, <em>reactR(v.0.6.1)</em>, <em>xfun(v.0.53)</em>, <em>S7(v.0.2.0)</em>, <em>cli(v.3.6.5)</em>, <em>withr(v.3.0.2)</em>, <em>magrittr(v.2.0.3)</em>, <em>crosstalk(v.1.2.2)</em>, <em>digest(v.0.6.37)</em>, <em>grid(v.4.5.2)</em>, <em>rstudioapi(v.0.17.1)</em>, <em>rappdirs(v.0.3.3)</em>, <em>lifecycle(v.1.0.4)</em>, <em>nlme(v.3.1-168)</em>, <em>coro(v.1.1.0)</em>, <em>vctrs(v.0.6.5)</em>, <em>mnormt(v.2.1.1)</em>, <em>evaluate(v.1.0.5)</em>, <em>glue(v.1.8.0)</em>, <em>GPArotation(v.2025.3-1)</em>, <em>farver(v.2.1.2)</em>, <em>rmarkdown(v.2.30)</em>, <em>purrr(v.1.0.4)</em>, <em>tools(v.4.5.2)</em>, <em>pkgconfig(v.2.0.3)</em> and <em>htmltools(v.0.5.8.1)</em></p>
</div>
</div>
</section><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script></main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside>
</div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Matthias Kloft.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

    </footer>
</div>





  </body>
</html>
